### ISSUE TITLE
Is sneakers require thread safe code?

### ISSUE THREAD

**Issue by Sen** [jondot/sneakers#109]
There is a old web app which i am maintaining, the app using sidekiq to run background jobs. But the worker was written in not thread safe(Mechanize) code, so sidekiq stucks sometimes.

I am considering switch to Resque. But seems sneakers is a great choice too. Is sneakers require thread safe code like sidekiq?

**Comment by michaelklishin** [comment]
You can [configure](https://github.com/jondot/sneakers/wiki/Configuration) it to use only one worker thread per process.

**Comment by Sen** [comment]
@michaelklishin looks like the problem resolved, thanks
