### ISSUE TITLE
`sneakers work` Should run all workers in app/workers

### ISSUE THREAD

**Issue by shaqq** [jondot/sneakers#110]
Major nitpick, but it'd be nice if the base command:

`sneakers work`

Looked up workers in `app/workers` or `lib/workers` and ran the ones that are Sneakers workers. That way, when I add a worker, I don't have to remember to update that command.

**Comment by jondot** [comment]
Hey @shaqq - would you be willing to sketch out how this might happen? I was thinking about a `sneakers-rails` gem maybe? what do you think?

**Comment by damonmorgan** [comment]
+1 for this. Although I'm not sure why rails would come into this? As for how this could work, you could do something like Hutch does - https://github.com/gocardless/hutch/blob/master/lib/hutch/consumer.rb#L10..L13
It would be good to simplify it further and just have to run `sneakers`
