### ISSUE TITLE
Feedback: Monit and PID's

### ISSUE THREAD

**Issue by AlexKlim** [jondot/sneakers#118]
Hi. 

Did you try to use sneakers with monit ? 
Do you think about pid/log files for each worker ?

It seems, it will be good deal to do it.

**Comment by jondot** [comment]
Hi Alex,
Thanks - I do not use monit in production, I use the combination of Upstart (Ubuntu) and Foreman for process management. 
For making sure processes doesn't exceed resource limits - I use any standard monitoring toolset like NewRelic/Sensu/Zabbix/etc.

Are you familiar with those?

**Comment by AlexKlim** [comment]
Ok, I understand. 

What about pid/log files for each worker ? For example, we have a lot of workers: It is cool to read log for each worker. 

And one more question, what will happen, when some worker is down ? Will Upstart or Foreman run the worker again ?

**Comment by jondot** [comment]
Upstart should bring it up again. The bonus is that Upstart is an operating system facility so you can trust it in a high degree of certainty.
Logs - Foreman will aggregate the logs for you and you can ask it to direct it to a log file of your choice.

**Comment by AlexKlim** [comment]
Thanks for your explanation. I will try to use Upstart and Foreman.
