### ISSUE TITLE
using a dead letter exchange

### ISSUE THREAD

**Issue by dbyron0** [jondot/sneakers#121]
I'd like to set things up so when I (or sneakers) reject(s) a message, rabbit routes it to a dead letter exchange, and then to a bound queue.  I've seen https://www.rabbitmq.com/dlx.html, but the only sneakers-specific info about dead letter exchanges I've found is in maxretry.rb and here: http://jondot.github.io/sneakers/blog/2014/11/21/what-weve-been-through.html.

The first thing I tried is adding

arguments: { :'x-dead-letter-exchange' => 'my-dead-letter-exchange' }

but that appears to not be enough, as bunny gives me this message in the log:

```
Unexpected error PRECONDITION_FAILED - inequivalent arg 'x-dead-letter-exchange' for queue 'portal_event_queue' in vhost '/': received the value 'my-dead-letter-exchange' of type 'longstr' but current is none
```

I thought I might get lucky and put the code to declare the exchange and a queue for it in the initializer method of my worker class, using @queue.exchange.channel to get to the channel.  Trouble is, the channel doesn't exist until after the initializer has finished.

So, then I figured I'd have to use a handler to set this up.  I tried the maxretry handler first since it does dead letter exchange-related things, but I'm faced with the same error.

Any ideas about what I'm missing?  I tried creating the dead letter exchange, but still see the same error.  Thanks for your help.

**Comment by rud** [comment]
I think you're simply hitting the RabbitMQ feature where a queue definition must be the same each time you declare it. Try completing all the messages in the queue, delete it, then try and re-declare it with the code that failed above. I think you'll find this particular error goes away (`but current is none`).

Hope this helps!

**Comment by rud** [comment]
An alternative if this queue cannot be deleted for any reason would be to setup a [Policy](https://www.rabbitmq.com/parameters.html#policies). These can be setup and changed at runtime without re-declaring the underlying queues and exchanges.

**Comment by michaelklishin** [comment]
Or use a policy to control optional arguments such as `x-dead-letter-exchange`, if possible.

**Comment by dbyron0** [comment]
Thanks for the help.  I deleted the queue and now the x-dead-letter-exchange argument works.  I have a followup question though.  What's the recommended place for putting the code to set up the actual dead letter exchange and its associated queue, assuming I'm using the oneshot handler?

**Comment by ajaysodhi** [comment]
Yes, The possible cause is, if you declare some queues manually, and later your program (client in code) tries to create one (based on the settings you had in code) then you get this error. The reason behind it is when your code (client application) tries to access one queue, it gets a signal from the server that the connection is not available for this.

## To solve this problem

- Delete all the queues that you have created manually, and let the client program create them by itself. 
- If you got problems in deleting the queues, because of some data is there in it, or for some reason, you want to maintain it, create one queue manually, and move all the queue data to be deleted in it through "Move" tab of the queue.

Hope that helps!!

**Comment by gpqhl0071** [comment]
> Thanks for the help. I deleted the queue and now the x-dead-letter-exchange argument works. I have a followup question though. What's the recommended place for putting the code to set up the actual dead letter exchange and its associated queue, assuming I'm using the oneshot handler?

I deleted the queue on the rabbitmq console and restarted the creation of the queue. The problem was solved perfectly.
