### ISSUE TITLE
 Allow binding to multiple exchanges

### ISSUE THREAD

**Issue by polmiro** [jondot/sneakers#127]
I'm in need to be able to hook the worker to multiple exchanges with they're own routing keys. Currently the only way I can achieve this is by creating one worker per exchange, or manually creating the binding to the new exchange (and the pain point which is maintaining that binding across environments).

Could we add an option to provide those exchanges + routing keys? I'd be happy to work on a PR for it.

I imagine having something like this:
```
class MyWorker
  include Sneakers::Worker

  from_queue 'my-queue',
    :exchanges => [
      {
        :name => 'my-first-exchange',
        :type => 'topic',
        :routing_key => [
          "my-routing-key-a",
          "my-routing-key-b",
          "my-routing-key-c"
        ]
      },
      {
        :name => 'my-second-exchange',
        :type => 'topic',
        :routing_key => [
          "my-routing-key-x"
        ]
      }
    ]
end
```

How does this sound?

**Comment by michaelklishin** [comment]
I think the right thing to do is to use Bunny directly, not reinvent its features with endless options.

**Comment by polmiro** [comment]
How would you go about maintaining bindings in different/new environments for that worker? Is there any way to run some initialization code for a worker? I guess I can manage some kind of inherited worker to perform them, but I was wondering if you had run into this or had some ideas on how to approach it.

**Comment by michaelklishin** [comment]
Having a way to initialise with arbitrary code (that has access to the underlying Bunny session and channel) is a very good idea.

**Comment by polmiro** [comment]
:+1:  I'll close this and try to send a PR with some initialization per worker solution.
