### ISSUE TITLE
build amqp url from multiple options from configuration file

### ISSUE THREAD

**Issue by RicardoBrazao** [jondot/sneakers#133]
I'm in my first tries with sneakers and one thing that is bugging me, is that in the configuration file you have the ```amqp```key with a string that has the url for the amqp. I know it's not a big of a deal but would you be interested in a pull request that adds keys to the configuration so the user doesn't need to create that url? Or did i miss some configuration options? If i missed i apologize in advance.
The configuration file would like something like this:
```ruby
  Sneakers.configure
                    :username => 'username',
                    :password => 'password',
                    :host => 'localhost',
                    :port => 5672
```
and then inside the sneakers gem we would create the amqp url based on those configurations.
Besides that awesome work with sneakers.
Regards.

**Comment by jondot** [comment]
Thanks Richardo, so you're interested in giving the AMQP host, port, credentials and so on in an explicit way rather than a URL?

**Comment by RicardoBrazao** [comment]
Yes, that's my objective. It's almost the same as you did with the ```vhost```option, of course i'll maintain the ```amqp```option for retrocompatibility.

**Comment by jondot** [comment]
@RicardoBrazao in order to support composability what if we just make a URL builder (my bet is that AMQP/bunny already has that?) that you use and pass:

```ruby
u = AmqpUrl.new(:username => ...
u.to_s
# amqp://..
Sneakers.new :amqp => u.to_s
```

**Comment by michaelklishin** [comment]
Bunny does [support URIs](http://rubybunny.info/articles/connecting.html#using_connection_strings).

**Comment by RicardoBrazao** [comment]
The thing is with that approach you're still delegating the logic of creating the amqp url to the user. I would like to make it an internal feature of the gem, so there's no logic on the user side in creating the url.

**Comment by jondot** [comment]
Thanks guys, closing as I feel this had been concluded. Please reopen if needed.
