### ISSUE TITLE
Maxretry is not used

### ISSUE THREAD

**Issue by NaixSpirit** [jondot/sneakers#136]
Code
```ruby
class AbilityWorker
  include Sneakers::Worker
  from_queue "download.abilities", handler: Sneakers::Handlers::Maxretry
  def work raw
    hash = MultiJson.load(raw)
    reject!
  end
end
```

Log

```
2015-06-03T10:27:14Z p-39663 t-oxlmi163w INFO: Maxretry handler [queue=download.abilities] msg=retrying, count=1, headers=
```

I waiting for long long time, and it not retry, only once

**Comment by justin-yesware** [comment]
Does the rejected message show up in the `<queue>-retry` exchange/queue? Also you might want to confirm that this exchange and associated queue have been setup correctly. Basically check that you have a queue named `<queue>_retry` that is bound to an exchange with the same name and that this queue has the x-dead-letter-exchange and x-message-ttl setting enabled.

**Comment by RmMsr** [comment]
It seems if you are missing the dead letter option to move failures into the retry queue. Try something like 
````
from_queue "download.abilities", handler: Sneakers::Handlers::Maxretry, :"x-dead-letter-exchange" => "download.abilities-retry"
````

**Comment by NaixSpirit** [comment]
@RmMsr Your are right, I forgot the dead letter option, thank you very much.
