### ISSUE TITLE
[1.0.4] Publisher not closing

### ISSUE THREAD

**Issue by junhanamaki** [jondot/sneakers#137]
Hello.

I was trying to get a feel of the performance of sneakers/rabbitmq, so I first tried to fill up a queue (to try to simulate worst case scenarios) with some messages by using the Publisher class provided by sneakers, as follows:

```ruby
500_000.times do
 Sneakers::Publisher
   .new(exchange: 'sneakers_bus', exchange_type: 'topic', heartbeat: 5)
   .publish('some message for queue yoh', routing_key: 'test_worker')
end
```
Running this, after publishing some messages it stops, displaying the message:

2015-06-05T09:39:16Z p-12941 t-ovid3fj4s DEBUG: Sending a heartbeat, last activity time: 2015-06-05 10:39:13 +0100, interval (s): 1

I understand this is a message from bunny, but if I replicate your code, and close the connection in the end all goes well (sure the rate of messages published takes a dive). So my question is, wouldn't it be safer to close the connection?

Thanks

**Comment by rud** [comment]
If I read your code correctly you're creating 500k publisher instances and publishing 1 message with each. Creating each `Publisher` means creating a fresh `Bunny` connection, and you're making 500k of those. The `Publisher` class is probably only intended to be instantiated a few times in a process as it does not allow for cleanup, effectively leaking a connected `Bunny` instance for instantiation where you call `.publish`.  The code is (I think, intentionally) naive, and mostly intended as an example of how to wire things together to get a message out the door.

In any case, do you see the same behaviour if you just reuse a single publisher?

**Comment by junhanamaki** [comment]
Using a single publisher works great. Also I ended up using bunny directly to feel the difference between publishing all messages using a single open connection vs opening a connection and closing after sending a message.

My question is more in the sense of the risk of not closing this connection, since by keeping the connection open it will (at some point in time) reach the same number of open connections that I reached and stop publishing. I guess the connection will be closed when the referencing object gets destroyed but... Just wanted to hear some opinion about this.

**Comment by rud** [comment]
The "officialest" documentation on this is in the wiki: https://github.com/jondot/sneakers/wiki/Publishing-messages - as I read it, the idea is to build your own publishing as there's no real consensus as to how this should be structured and how the lifecycle should be managed. It very much "depends".

To make this ticket actionable, I think it would be a neat idea to add comments to the publisher stating it's just an example, and you probably don't want to use this directly in production as there is currently no way to properly clean up created instances.

**Comment by junhanamaki** [comment]
Yes I agree that a heads up in the wiki would be neat, even though it was more of a doubt that I had so I'm ok in just closing this issue. Since I don't know if you want to make anything from this issue I'll keep it open and pass the responsibility of closing to you, if it is ok.

Thanks for the clarifications.

**Comment by jondot** [comment]
Yup, @rud is completely on the spot! some historical context here - since publishing usually doesn't involve much logic, in my case it usually was a "bare" bunny connection, and better yet - a different process in a different language (Golang) that is just used as a simple 'sink'.

This way, you defer all of the work to, well, your workers.

Having said that, the story is different when you're on a monolith Rails app. In that case, exactly like @rud mentioned you _do_ want to use a Sneakers-flavored publisher, in which case you'd be keeping a single publisher, just like keeping a single Redis connection, DB connection and so on.

I think this thread is an excellent discussion - I will link it to the Wiki page.
