### ISSUE TITLE
How to correctly set timeout on worker

### ISSUE THREAD

**Issue by aibraimov** [jondot/sneakers#142]
I have several workers and want them to run one job, which lasts one week. 
I set in config file: timeout_job_after => 1000x3600x24x7  
But it's still quitting after 3-5 hours with such errors

2015-07-09T18:07:46Z p-31408 t-ovgwqfnj4 ERROR: [worker-dashboard1.posts1:1:ub86p4][#<Thread:0x007fa4b9d97dc0>][dashboard1.posts1][#<Sneakers::Configuration:0x007fa4b9da48e0>] timeout

**Comment by lukaszkorecki** [comment]
@aibraimov wouldn't it be better to schedule same job every hour?

**Comment by taelor** [comment]
maybe try setting it on the worker's config call itself.

**Comment by aibraimov** [comment]
I solved this issue:
The problem was in bunny gem, normally i was creating channel fanout many times like this:
x = channel.fanout("blog.#{exchange}")
after i changed it to
x ||= channel.fanout("blog.#{exchange}")
it wasn't quitting anymore.
