### ISSUE TITLE
Problems with class loading in Rails production (like) environments

### ISSUE THREAD

**Issue by maxigs** [jondot/sneakers#15]
Hi,

there was a little issue with class loading (when processes/workers/threads are restarted i guess) that sometimes the workers did not load the rails environment properly.

Some errors like "circular dependency" or that methods on classes/objects are not found that should obviously be there.
It only happens in a environment where classes are cached (rails production or when otherwise activated).

The fix is to make sure the eager-loading the environment is manually triggered (which is deactivated by default for rake tasks).

Just add this line:

```
::Rails.application.eager_load!
```

Before doing anything else in the sneakers:run rake task and it works fine (did so far here).

**Comment by drewnichols** [comment]
I'm curious why this isn't built into sneakers:run rake task provided by the sneakers gem?

**Comment by sheerun** [comment]
+1 for this being built into sneakers. It caused problems with our production. Could you reopen?

**Comment by rud** [comment]
@sheerun: probably easiest to re-open as a pull-request. Just a thought :)

**Comment by nerikj** [comment]
Where did you add this line of code? In your own Rake task executing the sneakers:run task or in Rakefile?

I get "LoadError: No such file to load -- application_controller" all the time.

**Comment by drewnichols** [comment]
I created a `lib/tasks/sneakers.rake` to call this and then run the requested rake task

**Comment by nerikj** [comment]
Me too. Had to let the task depend on environment to not get the LoadError though. Don't know if this is correct but I'll try it out anyway.
```ruby
task run2: :environment do
  ::Rails.application.eager_load!
  Rake::Task['sneakers:run'].invoke
end
```

**Comment by n3bulous** [comment]
Just in case anyone lands here and wonders if it was added to the default rake task, it was on 2015.04.01: https://github.com/jondot/sneakers/commit/4f07a836fd1142c46702ea5267d4291d180c6da3
