### ISSUE TITLE
ServerEngine hangs

### ISSUE THREAD

**Issue by michaelbaudino** [jondot/sneakers#153]
Hello,

I updated Sneakers to `1.1.0` and I cannot run Sneakers workers anymore.

I tried both using `rake sneakers:run` and `sneakers work` but it does the same: everything hangs at some point and nothing happens.

I tracked down the hang to here: https://github.com/jondot/sneakers/blob/master/lib/sneakers/runner.rb#L12
Since I kept the default (and recommended, afair) setting of `daemonize: false`, I would not expect `@se.run` to return, but after calling this line, absolutely no log happens anymore and no `WorkerGroup` is ever instantiated (nor any of its methods are being called, indeed...).

Any idea about what could be happening, and how I could track this down more efficiently ?

**Comment by jondot** [comment]
Got it, thanks!
I'm trying to reproduce...

**Comment by jondot** [comment]
You're right, something changed in serverengine, latest version. I used 1.5.5 (minimum required by Sneakers) and everything works fine. So first step I'd recommend locking down to 1.5.5.
I'm continuing now in direction of serverengine to figure out what is going wrong.

**Comment by michaelbaudino** [comment]
Great, thanks :+1: 
Let me know if you need anything.

**Comment by jondot** [comment]
@michaelbaudino there it is. Somewhere along serverengine's logging infra, there was some race condition causing livelock.
Pushed v1.1.1 out right now.
Thanks for spotting this!

**Comment by michaelbaudino** [comment]
Thanks to you for such a quick reaction :sparkles: 
Also, I confirm it works with 1.1.1 :+1::+1::+1:

**Comment by jondot** [comment]
Awesome, happy times :+1:  :)

**Comment by michaelbaudino** [comment]
Fixed by fa66849790dbfafcf09f4a9f800947a3975eff25
