### ISSUE TITLE
nats.io

### ISSUE THREAD

**Issue by brodock** [jondot/sneakers#156]
Have you considered nats.io for this project?

**Comment by AlexRiedler** [comment]
@brodock as in having pluggable backends?

**Comment by brodock** [comment]
Yeah

**Comment by AlexRiedler** [comment]
@brodock sadly most of the code is rabbit centric, not much could be re-used if an implementation was done; I am not sure if there would be a huge advantage personally... Some of the rabbit terminology is different as well which would make things confusing.

The more I read about nats.io, its nice in theory; but not sure in practise. It seems closer to something like ZeroMQ + Memory Broker for storage.
e.g. how do you handle delayed retries?

Maybe you have a more convincing argument though?

**Comment by jondot** [comment]
I agree with @AlexRiedler, much of Sneakers' power comes from its unapologetic specialization with RabbitMQ. Doing pluggable backends would diminish that fact and undermine our product guarantees (which is directly imported from RabbitMQ's product guarantees, e.g. messaging semantics, reliability, and so on).
