### ISSUE TITLE
Track bunny-versions

### ISSUE THREAD

**Issue by rud** [jondot/sneakers#157]
Hi,

So, I see this in the [gemspec](https://github.com/jondot/sneakers/blob/bef0220618c773dc8177d9f4a95edc93de603c23/sneakers.gemspec#L20):
``` ruby
gem.add_dependency 'bunny', ['>= 1.7.0', '<= 2.0.0']
```

This means that the 2.0.0 version is allowed, but the 2.0.1 bug-fix version, or any other potential future 2.0.x.

If 2.0.0 is indeed a supported version, should the latter part of this not be `<= 2.1.0`? Or maybe move to just support a few bunny-versions by only using a `~> 2.0.1`, disallowing all 1.x versions.

Thoughts?

**Comment by michaelklishin** [comment]
Disallowing 1.x versions means Sneakers will require Ruby 2.0+. If that's OK, I'd simply depend on the latest stable version with `~>`.

**Comment by rud** [comment]
To my mind this would be a larger version bump, but aside from that 2.x is the supported ruby-series these days, right?

**Comment by jondot** [comment]
@rud yes i think you are completely right. @michaelklishin regarding Ruby, I think it is acceptable to require 2.0+ today, I'm assuming anyone wanting Ruby 1.9.x still, may use older versions of Sneakers.
Does that make sense?

**Comment by rud** [comment]
Does make sense. Maybe a short note in the changelog or the release tag denoting the ruby 2.x requirement going forward. 

Do you need a PR for this change?

**Comment by jondot** [comment]
Yup sounds right.
If you're keen on it, go ahead with the PR :) if not I'll probably make the changes you've mentioned soon :+1:

**Comment by michaelklishin** [comment]
@jondot if you bump major Sneakers version, it does (and exactly what my thinking was with Bunny).

**Comment by rud** [comment]
I've got my focus on a few other things, so please go ahead without me.

**Comment by jondot** [comment]
Sure thing, will do :)

**Comment by abezzub** [comment]
@jondot do you mind creating a new gem version? The latest one I see is 1.1.2: https://rubygems.org/gems/sneakers. 

Also does Sneakers support Bunny 2.1? It was released recently.

**Comment by jondot** [comment]
@abezzub sure, I'll cut a new version.  For 2.1 looks like there's a breaking change in the headers (http://blog.rubyrabbitmq.info/blog/2015/08/16/bunny-2-dot-1-0-is-released/), after a second review I think it is reasonable to bump to 2.1 since integers are only enlarged. therefore *only* those who worked around 32bit may be offended.

**Comment by jondot** [comment]
@abezzub new version is on Rubygems now :)

**Comment by michaelklishin** [comment]
@jondot FWIW so far we hear 0 complaints about integer serialisation changes in 2.1. 2.2 is [already out](http://blog.rubyrabbitmq.info/blog/2015/09/06/bunny-2-dot-2-0-is-released/) (nothing breaking or particularly important there there).

**Comment by jondot** [comment]
@michaelklishin awesome, I'll do another minor version to include 2.2 in, thanks!

**Comment by abezzub** [comment]
Thanks!

**Comment by jondot** [comment]
:+1:
