### ISSUE TITLE
Spawning workers and threads

### ISSUE THREAD

**Issue by michaldarda** [jondot/sneakers#161]
Hello,
I would like to verify if I'm thinking correctly.

Here is my usecase.

I have bunch of workers that consumes jobs from different queues. Some queues I want to process sequentially (one job at a time) and other one for example 4 jobs at a time.

```ruby
class OneByOneWorker
  include Sneakers::Worker

 from_queue: one_by_one, threads: 1
  # do some work
end
```

```ruby
class ParallelWorker
  include Sneakers::Worker

 from_queue: parallel_queue, threads: 4
  # do some work
end
```

should i spawn this workers together or separately?

I mean, should I invoke

`bundle exec sneakers work  OneByOneWorker, ParallelWorker`
or
`bundle exec sneakers work OneByOneWorker`
and then
`bundle exec sneakers work  ParallelWorker`

and what should my process value in configuration shall be?

I read guide end to end but obviously either I'm missing something or this is not mentioned.

Regards and thanks for awesome work 

EDIT: Ok I think i figured it out, i need to set `workers` configuration per worker (in` from_queue` method), the `OneByOneWorker` should have this variable set to 1, while the other one 4

**Comment by jondot** [comment]
Hi, sorry for missing out this thread. We're just finishing off a very long holiday season :)
You were correct on your finding. The processing model for Sneakers is a process-threads hybrid one:

1. Given N processes and K threads per process, you will always have N*K threads active.
2. Each worker class is assigned to N workers.
3. Each worker class can define threads K to use.

For example,
If you have MyWorker with 1 thread configured, and 4 processes configured. You will have 4 threads, but each of the 4 is allocated to 1 process. So essentially you will have a pure process-only model.

Hope this makes it even clearer

**Comment by michaldarda** [comment]
Now it is clear, thanks a lot :)

**Comment by rud** [comment]
Cool - think this can be closed :)

**Comment by jondot** [comment]
:+1:
