### ISSUE TITLE
rake sneakers:run fails with NoMethodError: private method `warn' called for nil:NilClass

### ISSUE THREAD

**Issue by selasiehanson** [jondot/sneakers#170]
Hello, 
I'm not sure if I am doing something wrong but in my rails app, anytime I run `WORKERS=ImageConverter rake sneakers:run`
I come up with the following error. I had the same issue in 2.2.1. I upgraded the gem to 2.3.0 and still the error persists. Any help will be appreciated.

 :/web_app# WORKERS=ImageConverter rake sneakers:run
rake aborted!
NoMethodError: private method `warn' called for nil:NilClass
/usr/local/bundle/gems/sneakers-2.3.0/lib/sneakers/runner.rb:43:in `reload_config!'
/usr/local/bundle/gems/sneakers-2.3.0/lib/sneakers/runner.rb:11:in `block in run'
/usr/local/bundle/gems/serverengine-1.5.11/lib/serverengine/config_loader.rb:39:in `call'
/usr/local/bundle/gems/serverengine-1.5.11/lib/serverengine/config_loader.rb:39:in `reload_config'
/usr/local/bundle/gems/serverengine-1.5.11/lib/serverengine/config_loader.rb:32:in `initialize'
/usr/local/bundle/gems/serverengine-1.5.11/lib/serverengine/daemon.rb:29:in `initialize'
/usr/local/bundle/gems/serverengine-1.5.11/lib/serverengine.rb:51:in `new'
/usr/local/bundle/gems/serverengine-1.5.11/lib/serverengine.rb:51:in `create'
/usr/local/bundle/gems/sneakers-2.3.0/lib/sneakers/runner.rb:11:in `run'
/usr/local/bundle/gems/sneakers-2.3.0/lib/sneakers/tasks.rb:38:in `block (2 levels) in <top (required)>'
Tasks: TOP => sneakers:run
(See full trace by running task with --trace)

**Comment by jondot** [comment]
I think this is due to not running Sneakers.configure anywhere. Create an initializer script in your Rails app and in it configure Sneakers like mentioned below:
https://github.com/jondot/sneakers/wiki/How-To:-Rails-Background-Jobs#global-configuration

Please let me know if that helps

**Comment by selasiehanson** [comment]
@jondot That works. Thanks a lot. I put the sneakers.rb in the config folder instead of config/initializers
