### ISSUE TITLE
Worker generator

### ISSUE THREAD

**Issue by jondot** [jondot/sneakers#172]
A couple years ago, I started building a sneakers worker generator. The idea was to have a CLI tool that is not Sneakers itself (to reduce noise in the main project); that was a premature optimization, since the original generator project kept getting more and more features until it stopped to a grind (I was out of free time) :).

I suggest building a small subsection within the Sneakers CLI module for a lightweight generator that will generate a worker and a rails initialization file.
- This is a 'fresh' task. It doesn't require any familiarity with Sneakers core codebase.

**Comment by michaelklishin** [comment]
I have a chance this won't happen any time soon => closing.
