### ISSUE TITLE
Message Retry Handler Feedback

### ISSUE THREAD

**Issue by imothee** [jondot/sneakers#18]
I was hoping to generate some discussion on the 'nicest' way to handle retries and errors in a Sneakers Handler.

I was playing around and came up with something like the following but it would require some changes to the way the worker handles acks/rejects and I wanted some feedback on it before I started pushing or making merge requests.

As you can see it would require the props and msg passed into the reject/error/timeout calls. It utilises a dead letter policy on the queue when called without requeue to push it into an exchange/queue with a ttl and a dead-letter-exchange setting of the originals sneakers exchange.

I'm also not sure about the best way to publish to an error exchange. I would have preferred a new error exchange to keep the routing_key the same instead of modifying the message but this also works.

Keen to get some feedback on it and the future direction.

Thanks for writing Sneakers!

```ruby
module Sneakers
  module Handlers
    class Maxretry
      
      ###
      # Maxretry uses dead letter policies on Rabbitmq to requeue and retry messages after a timeout
      # 
      ###

      def initialize(channel)
        @channel = channel
      end

      def acknowledge(tag)
        @channel.acknowledge(tag, false)
      end

      def reject(tag, props, msg, requeue=false)
        # Check how many times it has been requeued
        if props[:headers].nil? or props[:headers]['x-death'].nil? or props[:headers]['x-death'].count < 5
          @channel.reject(tag, requeue)
        else
        # Retried more than the max times
          @exchange.publish({:msg => msg, :routing_key => rops[:headers]['routing-keys'][0]}.to_json, :routing_key => 'error')
          @channel.acknowledge(tag, false)
        end
      end

      def error(tag, props, msg, err)
        reject(tag, props, msg)
      end

      def timeout(tag, props, msg)
        reject(tag, props, msg)
      end

      def noop(tag)

      end
    end
  end
end
```

**Comment by jondot** [comment]
Closing for cleanups :)
