### ISSUE TITLE
Use Sidekiq-like error handling collection

### ISSUE THREAD

**Issue by gabrieljoelc** [jondot/sneakers#188]
*Copied from https://github.com/jondot/sneakers/pull/184#discussion_r43554582*

The `raven-ruby` gem is what Sentry uses to hook into our apps, and it includes a [shim](https://github.com/jondot/sneakers/blob/master/lib/sneakers/worker.rb#L66-L68) for Sidekiq:
```ruby
raven-ruby/lib/raven/integrations/sidekiq.rb
Sidekiq.configure_server do |config|
  config.error_handlers << Proc.new {|ex,context| Raven.capture_exception(ex, :extra => {:sidekiq => context}) }
end
```
And then Sidekiq has a [method](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/exception_handler.rb#L20) that's invoked in their processing rescues that enumerates the `config.error_handlers` collection and passes the context hash to the interface method:
```ruby
# sidekiq/lib/sidekiq/exception_handler.rb
def handle_exception(ex, ctxHash={})
  Sidekiq.error_handlers.each do |handler|
    begin
      handler.call(ex, ctxHash)
    rescue => ex
      Sidekiq.logger.error "!!! ERROR HANDLER THREW AN ERROR !!!"
      Sidekiq.logger.error ex
      Sidekiq.logger.error ex.backtrace.join("\n") unless ex.backtrace.nil?
    end
  end
end
```
Sneakers should use a similar pattern. [`Sneakers::Worker#worker_error`](https://github.com/jondot/sneakers/blob/master/lib/sneakers/worker.rb#L112-L120) should enumerate the low-level error handlers (maybe "reporters" instead to avoid ambiguity with the already existing sneakers handlers) collection instead of logging things:
```ruby
# sneakers/lib/sneakers/worker.rb
def worker_error(msg, exception)
  Sneakers.error_reporters.each do |reporter|
    reporter.call(exception, { message: msg }) # add whatever else could be help for the worker context
  end
end
```
We could include a default reporter that copied sidekiq's default error [handler](https://github.com/mperham/sidekiq/blob/7a727c61cfd3f174d32e3a231b14833b61b897fe/lib/sidekiq/exception_handler.rb#L6-L15) and would log the message like you are wanting:
```
# sneakers/lib/sneakers/exception_reporter.rb
module Sneakers
  module ExceptionReporter
    class Logger
      def call(exception, context = {})
        Sneakers.logger.warn(context) if !context.empty?
        Sneakers.logger.warn "#{exception.class.name}: #{ex.message}"
        Sneakers.logger.warn exception.backtrace.join("\n") unless exception.backtrace.nil?
      end
    end
  end
end
```

**Comment by michaelklishin** [comment]
Hutch has a similar thing as well.

**Comment by jondot** [comment]
Im completely in favor, if you see a good value in it as long as it can be modular :) :+1:

The only reason Sneakers never had this kind of error reporting - is that typically it is used (both in my deployment and other close partner companies that use it) in an own-controlled server farm or cloud. 

In this scenario we always use our own logging infrastructure (graylog, splunk, etc.) rather a SaaS log collector, since in high performance scenarios we could not ensure that those 3rd parties won't affect our own processes since we want all kind of logs in the same place - errors and others (so also - no sensible deal in terms of price).
