### ISSUE TITLE
Problems Using Airbrake inside Sneakers

### ISSUE THREAD

**Issue by taelor** [jondot/sneakers#189]
I'm not exactly sure what's going on here, but I think it might have something to do with the timeout.rb library.

I'm trying to use Airbrake after rescuing errors inside of my work method, but I feel like timeout.rb is swallowing up the exception, and not letting the original caller deal with it.

Here is my test exception code:

```
def work(message)
    begin
      raise "Testing Exception: #{message}"
    rescue => exception
      msg = "#{exception.class}: #{exception.message}" rescue exception.to_s

      exception.backtrace.each do |bt|
        puts(" * #{bt}")
      end if exception.backtrace

      Airbrake.notify_or_ignore(
        :error_class => exception.class.name,
        :error_message => msg,
        :backtrace => exception.backtrace
      )
    end
    ack!
  end
```

That rescue block doesn't ever seem to run.

This is the stack trace I see from the sneakers worker:

```
2015-11-23T22:49:20Z p-4051 t-8h604 DEBUG: [worker-test_exceptions:1:k65wrj][#<Thread:0x00000001b28148>][test_exceptions][#<Sneakers::Configuration:0x000000049699d0>] Working off: Hello!
 * /consolo/consolo-warehouse/app/workers/exception_worker.rb:14:in `work'
 * /consolo/consolo-warehouse/vendor/bundle/ruby/2.1.0/gems/sneakers-1.0.3/lib/sneakers/worker.rb:58:in `block (3 levels) in do_work'
 * /consolo/consolo-warehouse/vendor/bundle/ruby/2.1.0/gems/sneakers-1.0.3/lib/sneakers/metrics/null_metrics.rb:8:in `call'
 * /consolo/consolo-warehouse/vendor/bundle/ruby/2.1.0/gems/sneakers-1.0.3/lib/sneakers/metrics/null_metrics.rb:8:in `timing'
 * /consolo/consolo-warehouse/vendor/bundle/ruby/2.1.0/gems/sneakers-1.0.3/lib/sneakers/worker.rb:54:in `block (2 levels) in do_work'
 * /usr/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
 * /usr/lib/ruby/2.1.0/timeout.rb:101:in `call'
 * /usr/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
 * /consolo/consolo-warehouse/vendor/bundle/ruby/2.1.0/gems/sneakers-1.0.3/lib/sneakers/worker.rb:53:in `block in do_work'
 * /consolo/consolo-warehouse/vendor/bundle/ruby/2.1.0/gems/thread-0.1.5/lib/thread/pool.rb:56:in `call'
 * /consolo/consolo-warehouse/vendor/bundle/ruby/2.1.0/gems/thread-0.1.5/lib/thread/pool.rb:56:in `execute'
 * /consolo/consolo-warehouse/vendor/bundle/ruby/2.1.0/gems/thread-0.1.5/lib/thread/pool.rb:392:in `block (2 levels) in spawn_thread'
 * /consolo/consolo-warehouse/vendor/bundle/ruby/2.1.0/gems/thread-0.1.5/lib/thread/pool.rb:359:in `loop'
 * /consolo/consolo-warehouse/vendor/bundle/ruby/2.1.0/gems/thread-0.1.5/lib/thread/pool.rb:359:in `block in spawn_thread'
```

**Comment by taelor** [comment]
Also I have confirmed that the rescue part of the block does in fact work. I can boot this into a console session and run the code in the block, and Airbrake sends out the notification, and I can see it logged in our error tracker.

**Comment by gabrieljoelc** [comment]
See #188

**Comment by taelor** [comment]
Actually, now that I've been digging into the Sneakers source code, I'm reminded of the "Handlers", so I'm thinking I could write a handler for :error and put the Airbrake notification code in there.

**Comment by gabrieljoelc** [comment]
Yes, that would work. However, #188 describes a way to keep reporting errors (error reporters) separate from handling sneakers' messaging semantics (handlers). Also see https://github.com/jondot/sneakers/pull/187#issuecomment-159063662

**Comment by taelor** [comment]
Ya, I'm going to have to agree with you.

I tried using Airbrake notify in the handler, I can see in the logs that its being called, but for some reason, it's still not sending anything.
