### ISSUE TITLE
Setup bindings after sneakers is initialized

### ISSUE THREAD

**Issue by adisos** [jondot/sneakers#190]
I'm putting message to fanout exchange from service1. And I want to bind specific queue to this fanout exchange in service2. How can I do that? 

This is my code:
```
#bin/worker
#!/usr/bin/env ruby

default_workers = %w(
  ApplicantsHandler
)

ENV['WORKER'] = ARGV[0] || default_workers.join(',')

require_relative '../config/environment'
require 'sneakers/runner'

r = Sneakers::Runner.new(ENV.fetch('WORKER', '').split(',').map { |w| w.constantize })
r.run
```

May be there is some method like `after_initialize`. Example:

```
r = Sneakers::Runner.new(ENV.fetch('WORKER', '').split(',').map { |w| w.constantize })
r.after_initialize do
  # setup bindings
end
r.run
```

**Comment by jondot** [comment]
You can take a look at the exchange configuration, https://github.com/jondot/sneakers/blob/master/lib/sneakers/configuration.rb#L9
`Sneakers.configure` can take configuration and you typically run that before all of your worker code. If this is rails, then `Sneakers.configure` can go in an initializer.

**Comment by jondot** [comment]
Closing as it seems to be resolved.
