### ISSUE TITLE
Worker breaks down with execution expired

### ISSUE THREAD

**Issue by ChristofferJoergensen** [jondot/sneakers#202]
I am running a Rails app that relies on Sneakers to exchange data between applications. I have noticed that during a worker process, if an operation takes too long the worker breaks down with `execution expired`. I encounter this issue when I fx. want to connect with some external resource that takes some time to respond, or if I write a large amount of data to my database, which takes some time. Any idea why this happens and how to avoid it?

My worker code is very basic:

``` ruby
class MyWorker
  include Sneakers::Worker
  from_queue "private.my_worker", env: nil
  def work(raw_message)
    begin
      message   = JSON.parse(raw_message)
      response  = HTTParty.post "https://sendgrid.com/api/mail.send.json", :body => {message['email_body']}
    rescue => e
      puts e # prints 'execution expired'
    end
    ack!
  end
end
```

In my Sneakers initializer, the heartbeat is set to 2:

``` ruby
Sneakers.configure({
  heartbeat: 2,
  amqp: "amqp://#{AMQP_CONFIG['RABBITMQ_USERNAME']}:#{AMQP_CONFIG['RABBITMQ_PASSWORD']}@#{AMQP_CONFIG['RABBITMQ_HOST']}:#{AMQP_CONFIG['RABBITMQ_PORT']}",
})
```

My bunny.yml looks like this:

``` ruby
default: &default
  RABBITMQ_HOST: '127.0.0.1'
  RABBITMQ_PORT: '5672'
  RABBITMQ_HEARTBEAT: 640
  CONTINUATION_TIMEOUT: 20000
  FRAME_MAX: 262144
```

The Rake taks that sets up Rabbitmq contains the following:

``` ruby
connection        = Bunny.new(connection_attrs)
connection.start
channel           = connection.create_channel
exchange          = channel.fanout("public.my_worker")
queue             = channel.queue("private.my_worker", durable: true)
queue.bind("public.my_worker")
connection.close
```

I don't think that the concrete action that trigger this is all too relevant, but here is the stacktrace of the worker breaking down because of a slow response on my request to the Sengrid API:

```
/home/me/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/protocol.rb:155:in `select'
/home/me/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/protocol.rb:155:in `rescue in rbuf_fill'
/home/me/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/protocol.rb:152:in `rbuf_fill'
/home/me/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
/home/me/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
/home/me/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
/home/me/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
/home/me/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
/home/me/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
/home/me/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
/home/me/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1384:in `request'
/home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
/home/me/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
/home/me/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:853:in `start'
/home/me/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1375:in `request'
/home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
/home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/httparty-0.12.0/lib/httparty/request.rb:93:in `perform'
/home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/httparty-0.12.0/lib/httparty.rb:486:in `perform_request'
/home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/httparty-0.12.0/lib/httparty.rb:439:in `post'
/home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/httparty-0.12.0/lib/httparty.rb:522:in `post'
/home/me/applications/myapp/releases/20160208150427/app/workers/my_worker.rb:7:in `block in work'
```

**Comment by NIHERASE** [comment]
I've had a similar problem, turns out sneakers' default job time limit is 5 sec. I don't think this is a "sane" default value and it was a pain to figure out what was actually going on.

Adding `timeout_job_after: 5.minutes` to the config hash solved the problem.
https://github.com/jondot/sneakers/wiki/Configuration

**Comment by ChristofferJoergensen** [comment]
@NIHERASE , tanks for you suggestion. This may be the right one, but I'm not sure it is.

Right now I can't trigger the `execution expired` exception regardless which `timeout_job_after` setting I use (which is usual for me - the exception only happens periodically), but if I for example add a `sleep(x)` line in the worker process it fails when `x` is higher than my current `timeout_job_after` variable. But it does not fail with the `execution expired` exception. Instead it fails with this error:

    2016-02-15T10:14:37Z p-61916 t-ousd6eaeg ERROR: [worker-private.my_worker:1:akwf9w][#<Thread:0x007f8bd90f0c50>][private.my_worker][#<Sneakers::Configuration:0x007f8bd90f1c68>] timeout

which is an error that I haven't seen before. So you are right, `timeout_job_after` does affect how long time a worker process can run, but it does not seem to be the kind of error that I have experienced. Do you agree?

**Comment by michaelklishin** [comment]
`Net::HTTP` timeout in a select doesn't seem to have much to do with Sneakers. The stack trace contains a worker implementation and HTTParty/REST client/Net::SSH lines.
