### ISSUE TITLE
Unable to log to stdout while using sneakers with Rails on docker

### ISSUE THREAD

**Issue by davekapp** [jondot/sneakers#206]
On a Rails 4.2.5 project, we are unable to get sneakers to log to stdout. Previously logging to a file worked, although it seems like that is not working for us at the current time either. We're trying to deploy our application using Docker and aggregating logs from the stdout of the containers is the way we'd like to go.

We are also a little confused about whether we can use Rails.logger inside of a sneakers process or not.

Any help or guidance would be very appreciated - we might just be going about things wrong.

Here's our current config/initializers/sneakers.rb:

```
Sneakers.configure runner_config_file: nil,
                   metrics: nil,
                   daemonize: true,
                   start_worker_delay: 0.2,
                   workers: 1,
                   log: 'log/sneakers.log',
                   pid_path: 'tmp/sneakers.pid',
                   env: nil,
                   durable: true,
                   ack: true,
                   threads: 2, # best to match prefetch
                   prefetch: 2, # best to match threads
                   timeout_job_after: 5,
                   exchange: 'services',
                   exchange_type: 'topic',
                   heartbeat: 5

Sneakers.logger.level = Logger::INFO
```

Replacing log: 'log/sneakers.log' with log: STDOUT does not work, unfortunately.

We are using the https://github.com/heroku/rails_stdout_logging to make Rails log to stdout in production, if that affects anything.

Thank you very much for any information or advice.

**Comment by justin-yesware** [comment]
Can you confirm that `log: STDOUT` does (or does not) work outside of a Docker environment? We configure sneakers with `log: STDOUT` and have never had an issue with sneakers logging not appearing in stdout. We generally do not use Rails.logger, but do use the underlying `Logger` class instance that we assign to Rails.logger. We're not using the gem you mention, but instead configure Rails.logger to use a Logger that writes to STDOUT. via a Rails initializer.

**Comment by davekapp** [comment]
Thanks for the suggestions Justin. I'll take a look at it and post back with findings.

**Comment by davekapp** [comment]
Thanks again Justin. To follow up on what I said, after much experimentation:

I read through the source and saw that in daemonized mode Sneakers sets up a logger automatically. I have had success _outside_ of a docker container with logging to a file in daemonized mode or to STDOUT in non-daemonized mode. (This is using Sneakers.logger rather than Rails.logger, which I stopped trying to use out of concern that the STDOUT logging gem might be interfering.)

Unfortunately, inside of a docker container, I am not seeing any worker instances log anything. Strangely, I do see the parent process (the one that spawns the actual workers) writing logs, such as
```
2016-02-24T16:16:40Z p-14248 t-bnql4 WARN: Loading runner configuration...
2016-02-24T16:16:40Z p-14248 t-bnql4 INFO: New configuration: #<Sneakers::Configuration:0x000000080b2838 @hash={:runner_config_file=>nil, ...
```

The actual workers, however, are not logging anything, daemonized or no. This makes me think the child processes inside the container are not actually getting access to the system resources needed to log, although that's more of a guess than a real conclusion.

**Comment by justin-yesware** [comment]
Hmm, yeah. I've not had experience running sneakers inside of a Docker container. We use foreman to run sneakers in our local development environment and have never had an issue with either Sneakers.logger or Rails.logger going to stdout. We deploy to heroku which injects the rails_stdout_logging gem into your rails app by default and again we have not seen any issue with it interfering with our ability to log. Sorry I can't offer anything else of much use.

**Comment by jondot** [comment]
Hey guys, I'm happy to join in on the discussion, @davekapp any chance to share the dockerfile or something that resemble it in terms of structure?

**Comment by davekapp** [comment]
Hi there, sorry for the delay @jondot . We had several things come up that ate up our time.

Our resident Docker expert said he had some things he wanted to try, and I'm not really clear on what he thinks might be changed to make this work. I'll see if I can follow up with any findings and a fix if found to help others avoid this.

**Comment by jondot** [comment]
Hi, check out [the latest commit](https://github.com/jondot/sneakers/commit/6fe74f3f6778998320e0c0517db839396788ee92) which packs a nice amount of Docker goodness in Sneakers. We can now run integration tests with docker-compose locally (even without this commit, they always run on TravisCI using their own infrastructure).
In addition there are two Docker build files for production and development that you can pick and use.

There's also a new `scripts` folder that holds example binaries that execute these use cases. If you run `scripts/local_worker` then you'd see docker-compose spinning a worker and RabbitMQ, and that worker will output stdout logs correctly like you'd expect. 

I hope this will help with your issue.

**Comment by davekapp** [comment]
Thanks @jondot , I really appreciate the help. We were able to get things working. Our ops team did a very big rebuild of how processes were managed in docker and we upgraded to the latest version and  and we are able to log normally to STDOUT.

**Comment by urbaez22** [comment]
It'd had been a great addition from you if you'd had posted which procedure you followed to fix your issue.
I've been facing the same issue for almost a week now, and can't figure it out, Sneakers' workers simply don't log anything to STDOUT, if I configure to log to a file, it does it, otherwise, it doesn't log anything (main thread does it, just like you indicated)..

**Comment by urbaez22** [comment]
> @urbaez22 i'm facing the same issue. Have you find any solutions for this problem?

I couldn't do anything, bro..

I just passed it over, and implemented it in Spring Boot, in a couple of days I had everything working like a charm, nad what's very important, under my control..

Cheers .
