### ISSUE TITLE
Feature request: Allow CLI to take pid_path and log as arguments

### ISSUE THREAD

**Issue by eReGeBe** [jondot/sneakers#214]
We're working on integrating sneakers with Capistrano with https://github.com/inventionlabsSydney/capistrano-sneakers/ (that gem is broken, we're also working on fixing it) and it would be ideal for us to be able to specify the pid_path and the log as options to the CLI to avoid having to specify them in a --require boot file, and leave the boot file to be whatever the project being deployed might need.

**Comment by eReGeBe** [comment]
I made a pull request #215  that implements this if you want to take a look at it.

**Comment by jondot** [comment]
merged, closing.
