### ISSUE TITLE
Worker local configuration is ignored - [FEATURE] Specify workers of each type

### ISSUE THREAD

**Issue by alexsotocx** [jondot/sneakers#219]
Hello,

I making some app for testing this excellent library but I'm trying to do local configuration and it's ignored
Check how I'm doing this

```ruby
gem 'sneakers', '2.3.5'
```

```ruby
#initializer sneaker.rb
Sneakers.configure({username: Rails.application.config.rabbitmq_user, password: 
Rails.application.config.rabbitmq_password, workers: 1, threads: 1, log_stdout: true, prefetch: 1, timeout_job_after: nil})

Sneakers.logger.level = Logger::INFO
```

```ruby
#Worker
class MassiveMessageWorker
  include Sneakers::Worker
  from_queue("queues.#{Publisher::QUEUE_NAMES[:massive_message]}_#{Rails.env}",{
    env: nil,
    ack: true,
    threads: 2,
    workers: 2,
    log_stdout: true,
    prefetch: 100,
    heartbeat: 2
  })

  def work(raw_message)
    puts "Im here"
    if MassiveMessage.process_enqueued_message(raw_message)
      ack! # we need to let queue know that message was received
    else
      requeue!
    end
  end
end
```

When I do ```WORKERS=MassiveMessageWorker rake sneakers:run```It ignores the local configuration...
#Output 
````
22:45:53 mm_worker.1 | 2016-05-24T03:45:53Z p-78380 t-owdmdyyvc WARN: Loading runner configuration...
22:45:53 mm_worker.1 | 2016-05-24T03:45:53Z p-78380 t-owdmdyyvc INFO: New configuration: #<Sneakers::Configuration:0x007fc5e58d3f08 @hash={:runner_config_file=>nil, :metrics=>nil, :daemonize=>false, :start_worker_delay=>0.2, :workers=>1, :log=>#<IO:<STDOUT>>, :pid_path=>"sneakers.pid", :amqp_heartbeat=>10, :timeout_job_after=>nil, :prefetch=>1, :threads=>1, :share_threads=>false, :ack=>true, :heartbeat=>2, :hooks=>{}, :exchange=>"sneakers", :exchange_options=>{:type=>:direct, :durable=>true, :auto_delete=>false, :arguments=>{}}, :queue_options=>{:durable=>true, :auto_delete=>false, :exclusive=>false, :arguments=>{}}, :amqp=>"amqp:/<redacted>@localhost:5672", :vhost=>"/", :username=>"eventtia", :password=>"eventtia", :log_stdout=>false, :handler=>Sneakers::Handlers::Oneshot, :logger=>#<ServerEngine::DaemonLogger:0x007fc5e58da150 @rotate_age=5, @rotate_size=1048576, @logdev_class=Logger::LogDevice, @progname=nil, @level=1, @default_formatter=#<Logger::Formatter:0x007fc5e58da0d8 @datetime_format=nil>, @formatter=Sneakers::Support::ProductionFormatter, @logdev=#<IO:<STDOUT>>>, :worker_type=>"process", :worker_classes=>[MassiveMessageWorker], :log_stderr=>false}>
```

Any help? or is it a bug?

**Comment by alexsotocx** [comment]
I was researching your code and I found this.
```ruby
    def from_queue(q, opts={})
        @queue_name = q.to_s
        @queue_opts = opts
      end
```
and the variable ```@queue_opts``` is never used again so in the version 2.3.5 the opts are ignored...
I'm going to open a pull request to solve this

**Comment by gabrieljoelc** [comment]
They are used in Worker#initializer as self.class.queue_opts.

**Comment by gabrieljoelc** [comment]
They are used in `Worker#initializer` as [`self.class.queue_opts`](https://github.com/jondot/sneakers/blob/master/lib/sneakers/worker.rb#L16).

**Comment by alexsotocx** [comment]
But for example I choose in the global configuration i chose 1 worker and in the Local configuration y chose 2 workers(See in the Log that I posted) it create just 1 worker  and the other config is ignored...

I had to workaround  using the global configuration in each file.
```ruby
Sneakers.configure({
    env: nil,
    ack: true,
    threads: 1,
    workers: 2,
    log_stdout: true,
    prefetch: 1,
    heartbeat: 2
})
Sneakers.logger.level = Logger::INFO

class MassiveMessageWorker
  include Sneakers::Worker
  from_queue "eventtia.queues.#{Publisher::QUEUE_NAMES[:massive_message]}_#{Rails.env}"

  def work(raw_message)
    puts "-----------------------------Proccesing message-------------------------"
    if MassiveMessage.process_enqueued_message(raw_message)
      ack! # we need to let queue know that message was received
    else
      requeue!
    end
  end
end
```

**Comment by gabrieljoelc** [comment]
@alexsotocx how many subscribers does your RabbitMQ admin say is subscribed to the queue? I'm wondering if it's a bug in just the Sneakers output.

**Comment by alexsotocx** [comment]
Hello it output 1.
![screen shot 2016-05-24 at 12 18 15 pm](https://cloud.githubusercontent.com/assets/6225534/15513312/ac7d616c-21a9-11e6-9653-9b99109fc9b1.png)
This is the code that i ran.
```ruby
#sneaker.rb in initializer
Sneakers.configure({username: Rails.application.config.rabbitmq_user, password: Rails.application.config.rabbitmq_password, workers: 1, threads: 1, log_stdout: true, prefetch: 1, timeout_job_after: nil})

Sneakers.logger.level = Logger::INFO
``` 
```ruby
#worker
class MassiveMessageWorker
  include Sneakers::Worker
  from_queue "eventtia.queues.#{Publisher::QUEUE_NAMES[:massive_message]}_#{Rails.env}", 
  {
    env: nil,
    ack: true,
    threads: 1,
    workers: 2,
    log_stdout: true,
    prefetch: 1,
    heartbeat: 2
  }

  def work(raw_message)
    puts "-----------------------------Proccesing message-------------------------"
    if MassiveMessage.process_enqueued_message(raw_message)
      ack! # we need to let queue know that message was received
    else
      requeue!
    end
  end
end
```

**Comment by gabrieljoelc** [comment]
@alexsotocx so here's the config breakdown:
```ruby
env: nil, # sneakers
ack: true,  # rabbitmq, queue
threads: 1,  # sneakers
workers: 2,  # sneakers
log_stdout: true,  # sneakers
prefetch: 1, # rabbitmq, channel
heartbeat: 2 # rabbitmq, connection
```
All the screenshot show is that the queue name was set correctly by the invocation to `from_queue` right? `prefetch` is at the channel level and `heartbeat` is at the connection level so you wouldn't see a "wrong queue config" error. `ack` is a queue level config, but `true` is the default so nothing would change. Can you try setting `ack` or `durable` to `false` and see if you get the "wrong queue config" error?

**Comment by alexsotocx** [comment]
Yes it throws an error... 
```
Unexpected error PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'eventtia.queues.massive_message_development' in vhost '/': received 'false' but current is 'true'
```
Even it's reading the local configuration  it  continues creating 1 workers(Or the default as 4 if no specified) as default :S

**Comment by gabrieljoelc** [comment]
@alexsotocx did you change durable in the worker config? if yes, it's "good" that it threw an error. it means that it tried to subscribe to a queue with the same name but a different `durable` setting.

**Comment by alexsotocx** [comment]
This is the repository: https://github.com/alexsotocx/sneaker-test with the my configuration
```
cd sneaker-test
bundle
rake db:create && rake db:migrate
rake rabbitmq:setup
foreman start
```

**Comment by gabrieljoelc** [comment]
If you want to subscribe to a queue with the same name but a different config, you will need to delete the existing queue and then re-run sneakers. For the non-queue-level configs that you are overriding in the worker e.g. `env`, `threads`, `workers`, `log_stdout`,  `prefetch`, and `heartbeat`, I'm not sure you can/need to override those in the worker. Why are you trying to override those in the worker?

**Comment by alexsotocx** [comment]
HI @gabrieljoelc 
Well, I'm not subscribing to the same queue
If you checked out the repository you can see that I have 2 types of workers ```MassiveMessageMailerWorker``` and ```MassiveMessageWorker``` 
The first one.
```ruby
from_queue "eventtia.queues.#{Publisher::RABBITMQ_NAMES[:massive_message_mailer]}_#{Rails.env}"
``` 

The second one subscribe to the queue
```ruby
from_queue "eventtia.queues.#{Publisher::RABBITMQ_NAMES[:massive_message]}_#{Rails.env}", 
```

Well in the configuration of the **second** I just need 1 worker with 1 thread because it has to be proccesed in order and 1 at the time, so the configuration must be:

```ruby
from_queue "eventtia.queues.#{Publisher::RABBITMQ_NAMES[:massive_message]}_#{Rails.env}", 
  {
    env: nil,
    ack: false,
    threads: 1,
    workers: 1,
    log_stdout: true,
    prefetch: 1,
    heartbeat: 2
  }
```
In the **first** It just send emails I need it to be done faster so the configuration will be:
```ruby
from_queue "eventtia.queues.#{Publisher::RABBITMQ_NAMES[:massive_message_mailer]}_#{Rails.env}", {
    env: nil,
    ack: false,
    threads: 2,
    workers: 2,
    log_stdout: true,
    prefetch: 2,
    heartbeat: 2
  }
```
You say 

> env, threads, workers, log_stdout, prefetch, and heartbeat, I'm not sure you can/need to override those in the worker.

Well I need it, but I think I can't based on this [wiki article](https://github.com/jondot/sneakers/wiki/Configuration) But It will be nice if you can specify the number of workers of each type.

Maybe later i make a pull request

**Comment by gabrieljoelc** [comment]
> Well, I'm not subscribing to the same queue
> If you checked out the repository you can see that I have 2 types of workers `MassiveMessageMailerWorker` and `MassiveMessageWorker`

I did look at the repo and saw both workers. I'm not referring to them being the same. I'm referring to the durable queue that was created for each worker the first time you started sneakers being configured with `durable: false`. Because they are durable they stay around so if you try to subscribe to the same queues on subsequent sneaker runs but with different queue-level configuration, you will get the "wrong queue config" error:
> > Unexpected error PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'eventtia.queues.massive_message_development' in vhost '/': received 'false' but current is 'true'

You would get a similar error if you changed the `ack: false` (see the bunny gem's ["Queue Re-Declaration"](http://rubybunny.info/articles/queues.html#queue_redeclaration_with_different_attributes) section for reference).

My original point here was that if you saw the error when overriding a queue-level config in your worker with a non-default value (i.e. `durable: false`, `ack: false`), you will see the error you saw and you will know that sneakers is correctly overriding the queue-level config values.

**Comment by alexsotocx** [comment]
@gabrieljoelc Thanks for the clarification 👍  

As I said it will be nice if you can specify the number of workers for a queue, currently sneaker is creating a pool of workers and it use all available to mitigate the current job. 

Well sometimes you need to process 1 queue item at a time, for example you have a heavy process(**Heavy**) and you don't want two process of that type to be mixed because it can kill the machine if you have cheap server with limited hardware.

So for example in the worker definition, specify the number of workers.
```ruby
from_queue :logs, workers: 1, threads: 1

def work()
//Do something
end
```

Nice library btw.

**Comment by gabrieljoelc** [comment]
@alexsotocx can you just set global configuration to `workers: 1, threads: 1`?

**Comment by alexsotocx** [comment]
@gabrieljoelc  Yes I can But it wont fit some people requirements.

For example my app.
We have an app that send mails to a lot of people based on some filters. The process of filtering is heavy process because we have a lot of people to apply filters. 

Also we have other worker to send the mail to the people filtered in the other worker, since this is cheap worker that just send the email we can do it faster, so I want to have 4 workers to make this fast.

So I don't want to specify 1 worker in the global configuration because we can have a lot of workers!

Thanks

**Comment by gabrieljoelc** [comment]
For your use case, could you solve by just running two different sneakers processes instead?
```ruby
# config/initializers/sneakers.rb
concurrency = ENV.fetch('SNEAKERS_CONCURRENCY', 1).to_i
Sneakers.configure({username: Rails.application.config.rabbitmq_user, password: Rails.application.config.rabbitmq_password, workers: concurrency, threads: concurrency, log_stdout: true, prefetch: concurrency, timeout_job_after: nil})

Sneakers.logger.level = Logger::INFO

# app/workers/massive_message_worker.rb
from_queue "eventtia.queues.#{Publisher::RABBITMQ_NAMES[:massive_message]}_#{Rails.env}"

# app/workers/massive_message_mailer_worker.rb
from_queue "eventtia.queues.#{Publisher::RABBITMQ_NAMES[:massive_message_mailer]}_#{Rails.env}"
```
```
1=> SNEAKERS_CONCURRENCY=1 WORKERS=MassiveMessageWorker rake sneakers:run
```
```
2=> SNEAKERS_CONCURRENCY=2 WORKERS=MassiveMessageMailerWorker rake sneakers:run
```

I don't think worker-level concurrency configuration is a feature sneakers would ever support necessarily (sidekiq doesn't support worker-level [concurrency](https://github.com/mperham/sidekiq/wiki/Advanced-Options#concurrency) configuration either). The concurrency is configured at the process level ergo it only can be changed in the global configuration.

**Comment by alexsotocx** [comment]
Yes Sidekiq doesn't support it by default but with a gem we can manage it. See this gem https://github.com/brainopia/sidekiq-limit_fetch :D

Maybe I make something similar in the future, by now I'm going to close this issue
