### ISSUE TITLE
It looks like rails is locking the sneaker log

### ISSUE THREAD

**Issue by jonheckman** [jondot/sneakers#224]
I am running into an issue in development when I am stress testing a worker.  
I have a decent amount of debug output in my worker which fills up the log quickly. It looks like it can't rotate the log because rails is locking it:  
If I kill the worker and restart it I get  

```
log rotation inter-process lock failed. Text file busy @ sys_fail2 - (log/sneakers.log, log/sneakers.log.0)
log writing failed. closed stream
log shifting failed. closed stream
log writing failed. closed stream
log shifting failed. closed stream
log writing failed. closed stream
log shifting failed. closed stream
log writing failed. closed stream
log shifting failed. closed stream
log writing failed. closed stream
log shifting failed. closed stream
log writing failed. closed stream
```

Checking the sneakers.log I get 

```
[jon@localhost log]$ lsof sneakers.log
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
ruby    29350  jon   12w   REG   0,37  1048640 4739 sneakers.log
[jon@localhost log]$ ps aux | grep "29350"
jon      13073  0.0  0.0 112648   976 pts/1    S+   21:50   0:00 grep --color=auto 29350
jon      29350  0.1  3.1 556964 153288 pts/0   Sl+  20:52   0:04 ruby /home/jon/.rvm/gems/ruby-2.1.2/bin/rails s
```

Killing the rails server allows me to delete the file.
I am running on centos. I can't reproduce this on the production server (centos) or when I was running the same code on my mac.

**Comment by jondot** [comment]
Hey @ninjonxb do you still have this problem?

**Comment by michaelklishin** [comment]
My best suggestion is to use a separate log file with Rails.
