### ISSUE TITLE
Possible to Pry?

### ISSUE THREAD

**Issue by taylorbrooks** [jondot/sneakers#225]
Is it possible use use `pry` in a Sneakers process?

https://github.com/pry/pry

**Comment by Spaceghost** [comment]
[pry-remote][].

[pry-remote]:https://github.com/Mon-Ouie/pry-remote

**Comment by lukegalea** [comment]
@taylorbrooks Were you able to get pry-remote working? I'm finding it's timing out, breaking in the wrong spot, etc.

I'm probably doing something trivially wrong but I just wanted to confirm that this works.

**Comment by taylorbrooks** [comment]
@lukegalea I was not able to get it working.

**Comment by lukegalea** [comment]
Dang. Me neither. @Spaceghost - any more hints to share? 

In the sneakers process, it actually appears to pry in there and the pry-remote process just exits:

```
[pry-remote] Waiting for client on druby://127.0.0.1:9876
[pry-remote] Client received, starting remote session
[pry-remote] Remote session terminated
[pry-remote] Ensure stop service

From: /home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pry-remote-0.1.8/lib/pry-remote.rb @ line 321 Object#remote_pry:

    319: def remote_pry(host = PryRemote::DefaultHost, port = PryRemote::DefaultPort, options = {})
    320:   PryRemote::Server.new(self, host, port, options).run
 => 321: end
```

Thanks in advance!
