### ISSUE TITLE
Deployment to production

### ISSUE THREAD

**Issue by pratik60** [jondot/sneakers#226]
How do you guys ideally deploy this?

So far, we have mainly relied on capistrano integration for deployment of separate background jobs runner.  For example -: Sidekiq - https://github.com/seuros/capistrano-sidekiq for sidekiq and capistrano integration.

The only one with a capistrano integration for sneakers is https://github.com/inventionlabsSydney/capistrano-sneakers, but I doubt it was ever working as it depends on something called sneakersctl which doesn't exist. I am guessing they just cloned the capistrano-sidekiq one, and have done a very half baked job at fixing it.

How would you advise that we go about deploying this? Keeping this in sync with code changes in the repository etc....

Any links to scripts, or any code whatsoever in the right direction would be incredibly helpful.

Thanks
Pratik

**Comment by adisos** [comment]
I use `foreman`.

There is an article about this tool - https://www.digitalocean.com/community/tutorials/how-to-set-up-zero-downtime-rails-deploys-using-puma-and-foreman

**Comment by pratik60** [comment]
We use capistrano puma, for our web servers -: https://github.com/seuros/capistrano-puma, which works really well tbh.

I am giving foreman + capistrano + sneakers a try now. Will ping if I need help :-)

**Comment by jondot** [comment]
Foreman is the best way to deploy Ruby apps, IMHO. Make sure to take a look at the [export facilities](https://github.com/ddollar/foreman/wiki/Exporting-for-production) in Foreman (they're sort of hidden from the eye on first look). This will let you use the native supervisor framework on each OS.

**Comment by jondot** [comment]
I'll close the issue for now, but feel free to keep a reference to it, or reopen if you feel you have more to discuss.
