### ISSUE TITLE
TLS verify_peer flag ignored

### ISSUE THREAD

**Issue by state-phasive** [jondot/sneakers#228]
When trying to configure Sneakers, the verify_peer flag is ignored.

`Sneakers.configure amqp: <path>, log: STDOUT, verify_peer: false`

Currently in development with some things that use messaging, we don't need TLS/SSL enabled for the time being but the development messaging service is setup for it (and it changes often).

**Comment by michaelklishin** [comment]
In master it is possible to pass any `Bunny::Session` instance you please, which means anything configurable in Bunny is configurable for Sneakers now.
