### ISSUE TITLE
Is possible to known when a Sneakers worker has a job done?

### ISSUE THREAD

**Issue by lmorais** [jondot/sneakers#230]
I need to know if a Sneakers worker has done your job or not, its possible?

**Comment by gabrieljoelc** [comment]
You could do this with the [`ack!`](https://github.com/jondot/sneakers/blob/master/lib/sneakers/worker.rb#L34) method.

**Comment by gabrieljoelc** [comment]
You could even publish another method to denote raising a semantic event that a specific work is done:
```ruby
class AnotherSweetWorker
  include Sneakers::Worker
  def work(msg)
    ack!
  end

  def ack!
    publisher.publish 'well done!', to_queue: 'another_sweet_job_completed'
  end
end
```

**Comment by lmorais** [comment]
Nice! Thank you for clarify
