### ISSUE TITLE
Code execution 8x slower using sneakers

### ISSUE THREAD

**Issue by kaikuchn** [jondot/sneakers#231]
Greetings!

First off, let me thank you for maintaining this great project! We're using sneakers in several apps without any trouble and we're loving it.
However, we recently stumbled upon a very strange case. We wanted to extract a background worker from a rails monolith into a separate service. We therefore switched from using [Que](https://github.com/chanks/que) to sneakers as a first step. We then noticed a performance degradation in the execution time of our background jobs by a factor of ~8.
This background process is very CPU intensive (5-30 seconds of 100% CPU usage, after switching to sneakers 8 times that).

While we do have some suspicions, we are unable to pin down the root cause. However, I have been able to come up with a simple example that shows similar characteristics. Just have a worker compute the following:

``` ruby
100_000.times { Time.parse(Time.utc(2016).iso8601) }
```

Using Ruby 2.3.1 this takes 3.5 seconds on my machine without using sneakers and 19 seconds using sneakers. I realise it is unfair to compare using sneakers against leaving it out but I guess we can all agree that 16 seconds overhead isn't what any of us would expect.

If you are able to reproduce this, do you have any idea what may cause this?

Best regards,
Kai

**Comment by jzernisch** [comment]
Same problem here, performance degrades significantly when using sneakers.

**Comment by brodock** [comment]
could be due to multiple context switch (threads)? 
try reducing the amount of threads and scaling with process only.

CPU intensive tasks get a lot of penalty with threads (because of the GIL).

**Comment by kaikuchn** [comment]
If I remember correctly we configured sneakers to spawn one worker per CPU.
I've created a small example to reproduce this issue https://github.com/kaikuchn/sneakers-issue-231 just clone and run it.

**Comment by jzernisch** [comment]
It seems to be related to the behavior of `Process.fork` on OS X. See http://stackoverflow.com/questions/38844392/why-does-process-fork-make-stuff-slower-in-ruby-on-os-x.

**Comment by kaikuchn** [comment]
Confirmed, this is an issue with OS X. But I guess pretty much about nobody uses that in production anyway so.. I'm closing this.
