### ISSUE TITLE
bunny gem reference is out of date

### ISSUE THREAD

**Issue by mtowers** [jondot/sneakers#232]
Sneakers currently references bunny 2.2.0 whereas the current release is 2.4.x.

New changes include some fixes for publishing which may address some of the issues reported here.

https://github.com/ruby-amqp/bunny/releases

**Comment by mtowers** [comment]
FYI: https://github.com/ruby-amqp/bunny/issues/424

**Comment by michaelklishin** [comment]
The current release is already `2.5.0` ;)

**Comment by pbollenbeck** [comment]
would be fixed with #235
