### ISSUE TITLE
How to have child processes catch a kill signal?

### ISSUE THREAD

**Issue by greggilbert** [jondot/sneakers#239]
On initialize in my worker class, I'm opening a connection to another UNIX socket so I can pump data into it. When the process is terminated, I'd like to be able to catch the kill signal so I can gracefully close the socket. I've tried doing all sorts of `Signal.trap` in and around the class, but nothing seems to work. 

Any ideas on how best to pull this off?

(For reference, I'm keeping the parent thread alive via `supervisord`.)

**Comment by greggilbert** [comment]
Edit: is this really as simple as `def stop` on the worker?

**Comment by michaelklishin** [comment]
Subclassing a worker could be an option but signal management is probably better done when things initialize. It's not something that is Sneakers-specific either way.
