### ISSUE TITLE
Skips records to enqueue from result set

### ISSUE THREAD

**Issue by kavitakanojiya** [jondot/sneakers#241]
Issue is:
I run rake every hour over a resultset that enqueues job for each record individually.
Lets say, I have an array of 360 elements. But when I run rake, this enqueues jobs for only 150-200 jobs and skips rest of the elements/results. I dont even see for rest of the records if they are published.
Can you help me to figure out this issue why rest of the results are skipped from publisher ?

Note: I run reindexing job for 3L users (reindex user/job ) and this works.

**Comment by michaelklishin** [comment]
We cannot suggest anything with the amount of information provided.
