### ISSUE TITLE
Any way to log sneakers logs remotely?

### ISSUE THREAD

**Issue by rootcss** [jondot/sneakers#245]
Hi,

Apart from STDOUT and file based logging, is there any in-built way with which we can log remotely eg, papertrail. For production use.
If there's no way, Could anyone suggest an already used method.

Regards.

**Comment by brodock** [comment]
Not an expert in sneakers, but: 

`Sneakers.logger = RemoteSyslogLogger.new(...)`
https://github.com/papertrail/remote_syslog_logger

**Comment by rootcss** [comment]
Thanks @brodock Have implemented it in similar way.

**Comment by krsyoung** [comment]
@brodock, just curious where you assigned the `Sneakers.logger` relative to the `Sneakers.configure`?

**Comment by brodock** [comment]
@krsyoung looks like the "correct way" is with `Sneakers.configure`: https://github.com/jondot/sneakers/blob/41883dd0df8b360c8d6e2f29101c960d5650f711/spec/sneakers/runner_spec.rb#L35

**Comment by michaelklishin** [comment]
(closed primarily because it's a question, although @brodock likely answered it)
