### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by groe** [jondot/sneakers#248]
Is there a changelog for sneakers?

It would be very helpful for maintenance and updates of existing applications relying on sneakers.

**Comment by michaelklishin** [comment]
I completely agree. We will put something together for the last release and start from there.

**Comment by groe** [comment]
Any news regarding the changelog? (What has changed in 2.4.0 and 2.5.0?)

**Comment by gabrieljoelc** [comment]
@groe @michaelklishin thoughts on me creating [releases](https://github.com/jondot/sneakers/releases) for each of the tags as a first pass?

**Comment by gabrieljoelc** [comment]
I'd probably just use [diffs](https://github.com/jondot/sneakers/compare/v2.4.0...v2.5.0) of the tags to copy in the PRs and descriptions in the tag releases.

**Comment by gabrieljoelc** [comment]
See #311 for a `v2.6.0` release proposal

**Comment by gabrieljoelc** [comment]
See for v2.6.0 release changelog https://github.com/jondot/sneakers/releases/tag/v2.6.0

**Comment by michaelklishin** [comment]
@gabrieljoelc thanks. Let's keep this one open for a bit more, I am happy to convert your release notes to a change log file similar to Bunny's.

**Comment by gabrieljoelc** [comment]
@michaelklishin ok. Yea, I was going to leave this issue open for the request in https://github.com/jondot/sneakers/issues/248#issuecomment-319283284.

**Comment by michaelklishin** [comment]
There's a breaking change in #307, so this is only growing in importance.
