### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by groe** [jondot/sneakers#249]
The latest release on rubygems is 2.3.5 and it's almost a year ago. There have been ~35 commits on github in the meantime (including updates to dependency gems like bunny from 2.2 to 2.5+), which are currently unreleased.

Are there any plans for the next release?

**Comment by felipecvo** [comment]
Any news?

**Comment by pchaganti** [comment]
👍

**Comment by michaelklishin** [comment]
@jondot WDYT? do you think you can grant me and @gabrieljoelc RubyGems release rights?

**Comment by michaelklishin** [comment]
@jondot bump.

**Comment by jondot** [comment]
Definitely, I'll need you guys' email addresses as the rubygems user

**Comment by luxflux** [comment]
@michaelbaudino, @jondot: Would be great to see a release to rubygems soon... If another dependency needs a newer bunny version, sneakers 0.0.7 will be installed 😄

**Comment by michaelbaudino** [comment]
I'm pretty sure you actually wanted to mention @michaelklishin, not me :wink:

**Comment by luxflux** [comment]
Yep, sorry... my fingers were too fast for my eyes... 😄

**Comment by ulissesalmeida** [comment]
I really would like to see this 7bd448f6877def81e333b400ab50bead6e88821e released 🙏

**Comment by michaelklishin** [comment]
@jondot my rubygems username is the same as on GitHub :) Thank you.

**Comment by michaelklishin** [comment]
@jondot ping.

**Comment by jondot** [comment]
@michaelklishin done!

**Comment by michaelklishin** [comment]
@jondot thank you! I will cut a new release soon, most likely tomorrow.

**Comment by jondot** [comment]
of course!

**Comment by michaelklishin** [comment]
`2.4.0` is up on rubygems.org.
