### ISSUE TITLE
Unacked messages?

### ISSUE THREAD

**Issue by lucas-aragno** [jondot/sneakers#252]
I'm getting my sneakers worker skipping like each 2 messages... I don't know if it has to do with my current set up

this is my sneakers initializer

```ruby
require "sneakers/metrics/logging_metrics"
Sneakers.configure amqp: ENV["AMQP_URL"],
                   metrics: Sneakers::Metrics::LoggingMetrics.new,
                   exchange: "my_exchange",
                   exchange_type: :direct
```

and my worker:

```ruby
require "json"

class RabbitmqWorker
  include Sneakers::Worker
  from_queue "my_queue"

  def work(raw_event)
    Rails.logger.debug "====== WORK"
    event_params = JSON.parse(raw_event)
    event_key = event_params.keys.first
    Rails.logger.debug "====== #{event_key}"
    case event_key
    when "some_message"
       # process here
    when "other"
        # process there
    else
       puts "Unkown message!"
    end
     ack!
  end
end
```

I've tried playing around with the configs but the behavior seems to be always the same... gets ~3 from each 5 messages 

I've Rails 4 + Puma server but I'm running this worker using `rake sneakers:run` any suggestions/ideas?

**Comment by michaelklishin** [comment]
First thing to do would be to make sure that all 5 messages are actually routed. Publishing messages as mandatory with a registered return handler is how you do it.
