### ISSUE TITLE
deploy worker on heroku rake sneakers:run exits status 0

### ISSUE THREAD

**Issue by patatoid** [jondot/sneakers#255]
Hi,

Trying to deploy sneakers on heroku, while I make a worker in my Procfile :
`worker: bundle exec rake sneakers:run`

It always exits on status 0 (success) but exits hence is killed, is there any way to make it keeping working ?

**Comment by michaelklishin** [comment]
It depends on what exactly is getting killed and why. Sorry, too little information to suggest anything.

**Comment by LucasPiffer** [comment]
You should try passing the name of the worker like

sneakers: WORKERS=XyzWorker bundle exec rake sneakers:run
