### ISSUE TITLE
Rails and overall structure / logging with Sneakers

### ISSUE THREAD

**Issue by krsyoung** [jondot/sneakers#256]
Hey folks,  

I am using RabitMQ to handle messaging between multiple components (Rails and Sinatra based) as well as within components when necessary (i.e. Rails to kickoff an async job from the web UI).  My Rails structure has two workers which are responsible for kicking off steps and for then processing the results.

My `Step` class inherits from `ActiveRecord::Base` which handles much of the work for running things (i.e. it makes a REST call or sends a message to another component to actually do some work).

The first problem I'm having is that my log messages seem to be lost.  I have the following in an initializer:

```ruby
# config/initializers/02_sneakers.rb
begin
  Sneakers.configure  daemonize: true,
                      amqp: "amqp://rabbitmq",
                      log: "log/sneakers.log",
                      pid_path: "tmp/pids/sneakers.pid",
                      threads: 1,
                      workers: 1,
                      exchange: 'dostuff',
                      exchange_type: 'direct'

Sneakers.logger.level = Logger::DEBUG
rescue Exception => e
  # bad, but otherwise precompile assets blows up in Docker
end
```

I do something like this in my worker:

```ruby
# app/workers/step_worker.rb

class StepWorker
  include Sneakers::Worker
  from_queue "run", env: nil, timeout_job_after: 12.hours

  def work(raw_event)
    logger.info { 'StepWorker received params: ' + raw_event }

    message = JSON.parse(raw_event)

    logger.debug { "StepWorker finding step for id: #{message['reference']}" }
    step = Step.find(message['reference'])

    logger.debug { "StepWorker running the step: #{step.name}" }
    begin
      step.run()
    rescue Exception => e
      logger.error { "error: exception while running step: #{e}" }
      step.error!
    end
    logger.info { "StepWorker completed processing event results for step: #{step.id}" }

    ack!
  end
end
```

All of these `logger` messages are printed in the `log/sneakers.log` file.   However, all of the logging statements within the `Step#run` method vanish.  

In general does this structure make sense and second is there some way to get my log messages to show?

**Comment by michaelklishin** [comment]
You catch `Exception`s and ignore them. Have you considered trying to leave at least some traces of what might have been raised?

**Comment by michaelklishin** [comment]
Does the backgrounded Sneakers process have a file handle for `` open? I wonder if this could be an effect of process forking on file handles (child processes must reopen all file handles to avoid descriptor sharing and all the confusing behaviours that it leads to).

**Comment by michaelklishin** [comment]
File descriptors can be inspected with `[sudo] lsof -p [pid]`, by the way.

**Comment by krsyoung** [comment]
Hi @michaelklishin, thanks for the ideas!  

To make a long story short I think I'm a dummy.  The worker logs to `sneakers.log` and the Rails classes to Rails' logger.  I seemed to be having issues correlating the two but after just testing now I do see the log messages (they are just split across the two logs).

However, now that I have found my log I can see there is an exception with a timeout to Redis happening consistently.  DB interactions seem to work no problem.  I will update this shortly with a picture of my architecture for review and see if it would somehow be causing the issues with Redis.

Regarding the Exceptions in the initializer, I 100% agree.  I need to revisit that and do something more intelligent to just not initialize Sneakers when running asset precompile / rake tasks etc..

---

And for future reference for others related to checking the log situation:

I've tried to capture some additional details.  Here is my general process table where we can see the two workers and the rails process:

```
root@91e6308bf529:/app/src# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  1.5  1.1 970440 72236 ?        Ssl  13:35   0:02 puma 3.6.0 (tcp://0.0.0.0:80) [src]                                         
root        29  0.0  1.3 583388 84328 ?        Sl   13:35   0:00 ruby /usr/local/bundle/bin/rake sneakers:run
root        33  0.1  1.3 994224 82020 ?        Sl   13:35   0:00 ruby /usr/local/bundle/bin/rake sneakers:run
root        67  0.0  0.0  20340  3272 ?        Ss   13:36   0:00 bash
root       130  0.0  0.0  17508  2144 ?        R+   13:37   0:00 ps aux
```

And we can see that both processes then have a reference to the `sneakers.log` file:
```
root@91e6308bf529:/app/src# lsof -p 29,33 | grep sneakers.log
ruby     29 root   13w   REG   0,32    82886   1755 /app/src/log/sneakers.log
ruby     33 root   13w   REG   0,32    82886   1755 /app/src/log/sneakers.log
```

**Comment by michaelklishin** [comment]
I'm sorry but a timeout to Redis is an environment-specific problem and out of scope for Sneakers issues.

**Comment by krsyoung** [comment]
@michaelklishin problem is it only happens when running via Sneakers ... the same thing natively with Rails works without issue (i.e. via Web UI or rails console).  If you're proposing StackOverflow community is better place that is fine ... but it is definitely Sneakers related. 

Was also hoping this issue could help provide some reference points for others who might be a little stuck with the Sneakers documentation.

**Comment by krsyoung** [comment]
@michaelklishin in the spirit of helping the community / sharing expertise are you able to confirm that the above architecture should work (particularly for logging)?  

I think I was correct in the first place that logging is not working for any ActiveRecord subclass (i.e. the Sneaker worker logs shows in `sneakers.log` but Rails logging doesn't show).  Do you know if it should show somewhere?

**Comment by michaelklishin** [comment]
I know nothing about your system, requirements or needs. The diagram looks OK. Plenty of people use Sneakers with Rails (I'm not one of them, however). Loading a Rails environment or parts of Rails from other apps can cause side effects and conflicts.

For example, every class that includes `Sneakers::Worker` inherently includes `Sneakers::Concerns::Logging`, which may override existing `logger` implementation. That's my best guess from the amount of information provided.

Logging and Redis connection issues, whether they are "Sneakers-specific" or not, are environment-specific issues. Those can only really be investigated by those who have access to the environment.

On an unrelated note, this issue is a good example of why I think Sneakers badly needs a mailing list.

**Comment by krsyoung** [comment]
@michaelklishin, I definitely second the last comment!  Maybe I should have gone to StackOverflow initially with this as the more appropriate community discussion form (lacking a mailing list).

I think you are spot on with your hypothesis about `Sneakers::Concerns::Logging`.  I have today booked to really sit down and figure these things out :-)

I very much appreciate your time, will update here again if I have something to share for future Sneakers users.

**Comment by gabrieljoelc** [comment]
@krsyoung are you running out of Redis connections?

**Comment by krsyoung** [comment]
@gabrieljoelc, thanks for the suggestion!  I will need to (figure out how to) check but I wouldn't think so.  Rational being:

- everything is running in Docker
- I kill everything and restart (i.e. Rails + workers container, redis container, postgres container etc.)
- I make a single request (should have max 2 redis calls) and things blow-up

I am doing some more debugging (and per previous discussion going to try to move this to StackOverflow as it is complicated beyond Sneakers).

For reference, my latest "problem" is that the calls just seem to be taking a very long time causing workers to timeout.  Here is an example of an HTTP get call and a Redis set call:

```
# via Sneakers / background job
HTTP get: 37.8922355520001
redis set: 20.88507309800002

# via rails c
HTTP get: 2.092669723000199
redis set: 0.13311994000014238
```

Making my head hurt!

**Comment by krsyoung** [comment]
@michaelklishin / @gabrieljoelc just wanted to summarize here (http://stackoverflow.com/questions/40695703/rails-network-calls-extremely-slow-from-sneakers-worker/40696494#40696494)

Net, not sneakers related (as Michael called).  I don't have the solution but the net is that the HTTP calls and the Redis calls ARE taking way too long and thus timing out the workers.

The logging issue is a big PITA but I can get around it by running Sneakers in the foreground and using STDOUT.  Seems that when daemonizing it can no longer log properly from classes that are subsequently called. 

Thanks again gents.

**Comment by michaelklishin** [comment]
@krsyoung `fork(2)` has known side effects on open file handles, including sockets, files, and pipes. [Long story short](http://www.linuxprogrammingblog.com/threads-and-fork-think-twice-before-using-them), child processes need to open new file handles/reconnect after `fork(2)`.
I wonder if you can define `logger` in your class and use `Rails.logger` or similar (assuming it still exists, I haven't used Rails in a number of years), and possibly make Rails re-initialize its logger after you know `fork(2)` happened and you are supposedly in a child process.

Worker timeout is a [configurable value](https://github.com/jondot/sneakers/blob/master/lib/sneakers/configuration.rb#L40), see [this workflow worker example](https://github.com/jondot/sneakers/blob/master/examples/workflow_worker.rb).

@gabrieljoelc has a point: if you run out of file descriptors (the default on Linux is 1024, so it's certainly possible to run over it even with a simplistic development environment workload). So it's worth checking (and bumping to 100K since the RAM price you pay for it is really tiny).

**Comment by krsyoung** [comment]
Hey @michaelklishin / @gabrieljoelc, thanks again for the ideas.  I spent an absurd amount of time debugging yesterday and got a little further.  I'll document here to hopefully help someone else in the future.

1. I ditched redis, in stepping back it just wasn't the right tool to use for what I was doing (so I didn't get to why it didn't work).  I did check file descriptors and it was big (1048576) although not sure if that is telling the truth in docker.  I was building the connection each time in a static class (not memoized) ... very strange (i.e. `StashService.get(key)`).  
2. The (real) timeout issue seems to be caused by how slow Rails is in rendering large JSON views.  I fixed it (> 5mins to ~13 s) by setting `config.assets.debug = false` in `development.rb`.
3. I'm still working through different approaches to getting the logging to show from within the Rails classes I call.  I was thinking of using a `after_fork` but haven't found the right place to put `sneakers.conf.rb`. @michaelklishin thanks for the help getting in the right direction re `fork`. 

Thanks for the pointer to the timeout info.  In my main workers (the services on the right-hand-side) I have set the timeout to ~12 hours but it seems to timeout right away (i.e. parsing the 10MB JSON file triggers a timeout).   Working through why that is happening as well.

Thanks guys!

**Comment by krsyoung** [comment]
I was finally able to get some level of logging working by assigning the `Sneakers.logger` to the `Rails.logger` in the worker.  I spent a significant amount of time trying to go the other way but did not have any luck.  The logging works perfectly when `daemonize: false` but falls down as soon as things are daemonized and logs are sent to STDOUT.

The result of the following is that the Rails logging messages will be displayed in the `log/sneakers.log` which isn't perfect but is better than no logging (in my Docker environment I typically have everything go to STDOUT).

Quick summary of the settings I used:

```ruby
# app/initializers/02_sneakers.rb 
  Sneakers.configure  daemonize: true,
                      log: "log/sneakers.log",
                      ...
```

```ruby
# step_worker.rb
class StepWorker
  include Sneakers::Worker
  from_queue "run", env: nil, timeout_job_after: 5.minutes, durable: true, ack: true

  def work(raw_event)
    ...

    # Assign the Sneakers logger to the Rails.logger
    Rails.logger = Sneakers.logger

    step = Step.find(message['reference'])

    # Assign the Sneakers logger to the Rails.logger
    Rails.logger = Sneakers.logger
    
    # yay, logging messages within ActiveRecord now work!
    step.run()

    ack!
  end
end
```

**Comment by deve1212** [comment]
what will be default timeout_job_after if we dont specify in config
