### ISSUE TITLE
reject! with the error message

### ISSUE THREAD

**Issue by c0mrade** [jondot/sneakers#268]
Hello, 

In my worker class I have it setup to `ack!` the message when everything goes well, however I also do have a rescue block that catches the exceptions and use `reject!` to reject messages and send them to the DLQ, works great btw!

However when I inspect my queue from my web client I see this (link is an image):

http://imgur.com/a/7Pb45

It would be nice if I could actually supply a message text or even use exception test, it would slightly help me troubleshoot potential issues.

Doesn't look like that's possible now:

https://github.com/jondot/sneakers/blob/master/lib/sneakers/worker.rb#L35

Or am I looking at the wrong code?

**Comment by michaelklishin** [comment]
There is no way for clients to provide a message with `basic.reject` or `basic.nack`, see [AMQP 0-9-1 quick reference](http://www.rabbitmq.com/amqp-0-9-1-quickref.html). The reason you're seeing is what RabbitMQ injects as the reason for dead-lettering.
