### ISSUE TITLE
How do you set a prefetch count per consumer vs per channel as per rabbitmq docs

### ISSUE THREAD

**Issue by achadee** [jondot/sneakers#270]
The rabbit mq docs specify that you can do a per channel prefetch and a per consumer, how does this work in sneakers with its configuration

https://www.rabbitmq.com/consumer-prefetch.html

**Comment by michaelklishin** [comment]
[Right here](https://github.com/jondot/sneakers/blob/41883dd0df8b360c8d6e2f29101c960d5650f711/lib/sneakers/queue.rb#L25-26).

**Comment by michaelklishin** [comment]
OK, consumer prefetch [is not exposed](https://github.com/jondot/sneakers/blob/41883dd0df8b360c8d6e2f29101c960d5650f711/lib/sneakers/queue.rb#L52) is it is not a commonly used setting.

**Comment by michaelklishin** [comment]
Note that in projects such as Sneakers it is very common for each worker (or similar) to use a separate channel, in which case per-consumer prefetch won't make any practical difference.
