### ISSUE TITLE
Don't include amqp connection options in logs

### ISSUE THREAD

**Issue by stevenkaras** [jondot/sneakers#28]
Currently, [Sneakers::Worker#worker_trace](https://github.com/jondot/sneakers/blob/master/lib/sneakers/worker.rb#L108) logs the queue options, which can contain sensitive authentication information (username/password).

The connection details should be scrubbed (only display scheme://host:port/path) prior to being displayed, or omitted entirely (not ideal, as it does provide useful information)

**Comment by rud** [comment]
@stevenkaras I think that was an encouragement for a PR if you're up for it :)

**Comment by ngrennan-inflection** [comment]
I created PR #101 to redact just the password. I think the not mentioning the amqp is going too far. I also think redacting the username is going to far. Usernames are in logs all the time.
