### ISSUE TITLE
Dead code or what?

### ISSUE THREAD

**Issue by meetme2meat** [jondot/sneakers#281]
Looking at the sneakers code base I see [this ]( https://github.com/jondot/sneakers/blob/master/lib/sneakers/workergroup.rb#L28-L30). As I see currently the workers supplied to `serverengine` from [here](https://github.com/jondot/sneakers/blob/master/lib/sneakers/tasks.rb#L40) and [here](https://github.com/jondot/sneakers/blob/master/lib/sneakers/cli.rb#L74) are basically an `Array` object and If that is true then I believe the following condition `worker_classes.respond_to? :call` always result in `false` check.

If all the above is true I would like to propose a pull request for the removing that dead code.

**Comment by michaelklishin** [comment]
That code doesn't seem to be accidental, just a fairly common idiom of supporting callables that produce final configuration values. In a dynamically typed language it's not as crazy as it may sound
and sometimes this form of lazy initialization can make a difference.

It could be specific to a particular (e.g. older) `serverengine` version, too.
