### ISSUE TITLE
Adding and removing workers dynamically

### ISSUE THREAD

**Issue by ionutzp** [jondot/sneakers#286]
Hi @jondot is there a way to achieve this at the moment? I'm trying to do it this way:

```
$runner = Sneakers::Runner.new([XWorker])
$runner.run
$runner.instance_variable_set("@runnerconfig", new_runner_config)
$runner.instance_variable_get("@runnerconfig").reload_config!
```
Is there a better way to do this? I've tried `$runner stop` but it doesn't work properly.

Thanks

**Comment by michaelklishin** [comment]
I am not @jondot but a quick inspection of `Runner` and `Configuration` suggests there was no intent to support this.

I cannot comment on "it doesn't work properly" due to how specific it is.

**Comment by ionutzp** [comment]
thanks @michaelklishin 
any ideas on how to achieve this? i'm building a rails application that has to subscribe to queues dynamically

**Comment by michaelklishin** [comment]
@ionutzp "subscribe to queues dynamically" is still not very specific. You can subscribe and unsubscribe any time with Bunny. Sneakers offers [an "auto-scaling" feature](https://github.com/jondot/sneakers/wiki/Configuration#auto-scaling-configuration) but it may or may not be exactly what you need.
