### ISSUE TITLE
Memory Increase each time consumed from a queue

### ISSUE THREAD

**Issue by chelope** [jondot/sneakers#293]
I'm using sneakers to consume XML files from a queue, the application that publishes the XML files can drop off a lot of XML in the queue. I realized that every time that the application consumes from the queue the memory increases (it's normal) but after to finish to consume all the files the memory doesn't decrease again, so this causes the memory reach 100% later on.

I tested the same process but using an REST endpoint instead to use sneakers, using that approach the memory increases during the processing and then decreases after the processing of files.

For any reason the memory is not being freeing using sneakers, or maybe I'm doing something wrong.

This is my sneaker configuration:

``` ruby
class LoadPatientWorker
  include Sneakers::Worker
  include ApplicationHelper
  from_queue 'pophealth.qrda1.queue',
             :timeout_job_after => 60,                 # Maximal seconds to wait for job
             :prefetch => 5,                                 # Grab 10 jobs together. Better speed.
             :threads => 5,                                 # Threadpool size (good to match prefetch)
             :share_threads => true,
             :env => ENV['RACK_ENV'],                   # Environment
             :ack => false,                             # Must we acknowledge?
             :heartbeat =>30,                           # Keep a good connection with broker
             :hooks => {},                              # prefork/postfork hooks
             :start_worker_delay => 10,                 # Delay between thread startup
             :exchange => 'exchange1',
             :exchange_options=>{:type=>:fanout,
                                 :durable=>true,
                                 :auto_delete=>false,
                                 :arguments=>{}
              },
             :queue_options=>{:durable=>true,
                              :auto_delete=>false,
                              :exclusive=>false,
                              :arguments=>{:'x-dead-letter-exchange' => 'exchange.error', :'x-dead-letter-routing-key' => 'rkey.failure'}}
  def work_with_params(msg, headers, params)

    Sneakers.logger.debug "Message recieved:  #{msg}"

    practice = get_practice_parameter(params[:headers]['practice_id'], params[:headers]['practice_name'])

    success = BulkRecordImporter.import(msg, {}, practice)
    if success
      puts 'Patient Imported'
    else
      puts 'Patient record did not save properly'
    end

  end
end
```

Please your help

**Comment by michaelklishin** [comment]
Start with looking at the number of unacknowledged messages in RabbitMQ management UI and then run your code with a [memory profiler](https://github.com/SamSaffron/memory_profiler).

Try using a no-op (blank) `work_with_params` to compare: if the behavior persists then it's likely something in Sneakers and not your code.

Another great thing to try is with [manual acknowledgements](http://www.rabbitmq.com/confirms.html) and a reasonable prefetch ([e.g. 100](https://www.rabbitmq.com/blog/2014/04/14/finding-bottlenecks-with-rabbitmq-3-3/)), otherwise Sneakers consumers can be overwhelmed since RabbitMQ will deliver messages as fast as possible, without any kind of flow control, regardless how quickly they are actually processed.

Since Sneakers requires Ruby 2.0+, you have more GC stats available: see [relevant](https://samsaffron.com/archive/2013/11/22/demystifying-the-ruby-gc) [posts](https://thorstenball.com/blog/2014/03/12/watching-understanding-ruby-2.1-garbage-collector/).

**Comment by chelope** [comment]
@michaelklishin thanks for your response, I have looked at the unacknowledged messages in RabbitMQ management UI  and all the messages are acknowledged. I tried also the manual acknowledgments and increased prefech to 100. In addition, to that I commented my code in work_with_params in order to avoid any additional memory consumption of my code but the behaviour is memory consumption is the same.


class LoadPatientWorker
  include Sneakers::Worker
  include ApplicationHelper
  from_queue 'pophealth.qrda1.queue',
             :timeout_job_after => 60,                 # Maximal seconds to wait for job
             :prefetch => 100,                                 # Grab 10 jobs together. Better speed.
             :threads => 5,                                 # Threadpool size (good to match prefetch)
             :share_threads => true,
             :env => ENV['RACK_ENV'],                   # Environment
             :ack => true,                             # Must we acknowledge?
             :heartbeat =>30,                           # Keep a good connection with broker
             :hooks => {},                              # prefork/postfork hooks
             :start_worker_delay => 10,                 # Delay between thread startup
             :exchange => 'exchange1',
             :exchange_options=>{:type=>:fanout,
                                 :durable=>true,
                                 :auto_delete=>false,
                                 :arguments=>{}
              },
             :queue_options=>{:durable=>true,
                              :auto_delete=>false,
                              :exclusive=>false,
                              :arguments=>{:'x-dead-letter-exchange' => 'exchange.error', :'x-dead-letter-routing-key' => 'rkey.failure'}}
  def work_with_params(msg, headers, params)

    Sneakers.logger.debug "Message recieved:  #{msg}"

    #practice = get_practice_parameter(params[:headers]['practice_id'], params[:headers]['practice_name'])

    #success = BulkRecordImporter.import(msg, {}, practice)
    #if success
      puts 'Patient Imported'
   # else
   #   puts 'Patient record did not save properly'
   # end
   ack!
  end
end

**Comment by bronislav** [comment]
@chelope Did you able to solve this? I'm experiencing same behaviour and going to profile my worker. But maybe you have some suggestions?
