### ISSUE TITLE
"Scrape-Web-Pages#Resource Starvation" - documentation not clear enough

### ISSUE THREAD

**Issue by pavlo** [jondot/sneakers#294]
Hey!

The [Scrape-Web-Pages#Resource Starvation](https://github.com/jondot/sneakers/wiki/How-To%3A-Scrape-Web-Pages#resource-starvation) section states that the database driver won't keep up given Sneakers opens up many processes and threads:

> If you are thinking of adding a persistence layer here (for example, for saving the page titles), note that the fact that Sneakers opens up to so many threads and so many processes, may mean that your database driver won't keep up. You'll need to make it accept more concurrency - check Performance for more on this.

It refers to [Performance](https://github.com/jondot/sneakers/wiki/Performance) page as a source of details on the issue - where I humbly expected to get more insights on why a database driver would give up and what is the recommended way to handle cases like that - but it does not have any information relevant to resource starvation it seems.

Can you please explain the issue in more details - why would it cause issues to a DB driver, what points should be taken in consideration when designing a system like that? How would you recommend to deal with data persisting (in this particular case)? 

Once the matter is clear, I can help you out reflecting it on the WIKI page(s) if you're okay with that...

**Comment by michaelklishin** [comment]
@pavlo that's a bold claim, I will edit it to say that it might cause contention but without knowing what data store is used, with what settings and so on it's nothing but a speculation.

**Comment by pavlo** [comment]
Thank you @michaelklishin, your edit on the WIKI page makes sense and answers my question perfectly.
