### ISSUE TITLE
Fix master build test failure

### ISSUE THREAD

**Issue by gabrieljoelc** [jondot/sneakers#299]
https://travis-ci.org/jondot/sneakers/builds/244338929

**Comment by michaelklishin** [comment]
Was addressed in ac2d572e73f6e938746d75ca688cc03f8e5709ee by @aiomaster. Thank you.

**Comment by michaelklishin** [comment]
I hopefully fixed an unrelated ruby-fprof installation error on ruby-head that broke Travis.
