### ISSUE TITLE
Unacked messages

### ISSUE THREAD

**Issue by delef** [jondot/sneakers#303]
Sometimes sneakers stops reading messages and gives away just unacked. Tested many times, do not really want to rewrite on the bunny.

**Publisher (PHP)**:
```
$exchange = new \AMQPExchange($this->channel);
$exchange->setName('admin');
$exchange->setType(AMQP_EX_TYPE_DIRECT);
$exchange->setFlags(AMQP_DURABLE);
$exchange->declareExchange();

$queue = new \AMQPQueue($this->channel);
$queue->setName('admin.statistics');
$queue->setFlags(AMQP_DURABLE);
$queue->declareQueue();
$queue->bind($exchange->getName());

$message = [
  'daily' => [['app_id' => 1, 'country_code' => 'EN', date: '2017-07-13'], ...], # n > 20 && n < 100
  'active' => 1
];

return $exchange->publish(json_encode($message));
```

**Sneakers init**:
```
require 'sneakers'

Sneakers.configure({amqp: 'amqp://guest:guest@localhost:5672', pid_path: 'sneakers.pid'})
Sneakers.logger.level = Logger::WARN
$WORKERS = [StatisticsWorker]
```

**Worker**:
```
class ReportSessionsWorker
  include Sneakers::Worker
  from_queue 'admin.statistics'

  def work(message)
    begin
      report = JSON.parse(message)

      report['daily'].each do |rd|
        attrs = {app_id: rd['app_id'], country_code: rd['country_code'], date: rd['date']}
        rd['active'] = report['active']

        if ReportSession.exists?(attrs)
          ReportSession.find_by(attrs).update_attributes(rd)
        else
          ReportSession.create(rd)
        end
      end
    rescue
      reject!
    ensure
      ack!
    end
  end
end
```

Help me please 😢

**Comment by michaelklishin** [comment]
Start with inspecting queues and channels that have unacknowledged deliveries in the management UI as well as [prefetch values used](http://www.rabbitmq.com/confirms.html).

Then Sneakers, Bunny and server logs for clues. Bunny can be instructed to log every single frame by setting its log level to `debug`, e.g. with exporting `BUNNY_LOG_LEVEL=debug` before starting the process.

Your code can result in double acknowledgements: you reject in a `rescue` block and ack in an `ensure` that follows, after which the channel will be closed and there will be no deliveries (or any other activity) on it.

Taking a traffic capture [Wireshark](https://www.rabbitmq.com/amqp-wireshark.html) will provide a good insight into what's really being sent by both server and client.

**Comment by christianhellsten** [comment]
This issue is caused by the "ensure" block. As demonstrated here the block returns "noop" and not "ack!:
```
def hello
  begin
    "noop"
  ensure
    "ack!"
  end  
end

hello()
=> "noop"
```

See:
https://github.com/jondot/sneakers/wiki/Creating-a-Worker#job-control

> Please mind that you have to return this signal from work method. Either make it a last line of work method or use explicit return statement.

**Comment by michaelklishin** [comment]
@christianhellsten thank you for following-up.
