### ISSUE TITLE
Provide worker class to error reporters

### ISSUE THREAD

**Issue by jdlombardozzi** [jondot/sneakers#306]
I need further context as to which worker an exception occurred. Simple solution is to provide the class to the error reporter handler. This will provide more options for the handler. In my case, I want to direct the error to a worker specific logger. I currently do a worker specific logger for each worker class, but unless I override the work method or rescue all exceptions within that method I am unable to log the error to my expected logger.

**Comment by michaelklishin** [comment]
Addressed by #307.
