### ISSUE TITLE
Dealing with dead letter queues

### ISSUE THREAD

**Issue by c0mrade** [jondot/sneakers#310]
Hello I went trough all articles that I could find on this project, including https://github.com/jondot/sneakers/wiki/Message-handling-semantics

And I've implemented DLX binded to a DLQ in my project. Message which errors out for whatever reason gets rejected using `reject!` and it ends up on my DLQ which I can inspect.

Problem is that most of the time, I can figure out the issue what happened by replaying the message locally with the same version of the code in production.

However in this case I see messages get rejected but unable to reproduce it locally. How do you handle this case? Like ideally I would want to know the reason why the message got to the DLQ as soon as I see it, as is now with the `reject!` method I know something went wrong, just not sure what.

What is the proper way of handling this, is it possible to add the actual error as some kind of message metadata which would be available for people troubleshooting or how is this done as in the best practice?

Is it me having my own handler where I could define reject like so :
```

def reject(tag, requeue=false)
   @channel.reject(tag, requeue)
end
```
Referencing https://github.com/jondot/sneakers/wiki/Message-handling-semantics again.

Thanks

**Comment by michaelklishin** [comment]
We cannot suggest much without a step by step way to reproduce. Please help others help you.
