### ISSUE TITLE
sneakers_rails integration

### ISSUE THREAD

**Issue by essamhassan** [jondot/sneakers#313]
# Suggestion
I made a gem to integrate sneakers with rails and automate the process in `https://github.com/jondot/sneakers/wiki/How-To:-Rails-Background-Jobs`

Interested to hear feedback and maybe include the gem into the docs here

https://rubygems.org/gems/sneakers_rails

**Comment by michaelklishin** [comment]
Thanks. It's at 0.0.3, perhaps it can mature a bit before we begin recommending it.
