### ISSUE TITLE
Heartbeat memory consumption

### ISSUE THREAD

**Issue by michaelbaudino** [jondot/sneakers#317]
Hi there,

I realized that setting `heartbeat` value too low can cause a massive increase of memory usage 😱 

Here is our production memory usage graph for the exact same setup (`{workers: 4, threads: 10, prefetch: 10, share_threads: true}`) with `heartbeat: 2` and `heartbeat: 2000`:

![sneakers-heartbeat-annotated](https://user-images.githubusercontent.com/1447321/30445609-d43d2c4a-9986-11e7-9dd7-0f5cdef0d5e1.png)

As you can see, using `heartbeat: 2` is using approximately twice as much RAM as `heartbeat: 2000`.

Is it known? Is it expected? Is there anything we can do?

**Comment by michaelklishin** [comment]
@michaelbaudino see [Low Timeout Values and False Positives](http://www.rabbitmq.com/heartbeats.html). I highly recommend against using a 2 second value (as well as 2000, which will be as good as having no heartbeats at all for all intents and purposes).

The heartbeat implementation in Bunny is [pretty straightforward](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/heartbeat_sender.rb). My best guess is that with such a low value your app started running into false positives (see Bunny and server logs) and reconnect.
I just don't see what else in `Bunny::HeartbeatSender` can consume a lot of RAM, so use a memory profiler if you are really curious.

Sorry but this chart alone is no evidence of an issue in Bunny. Who knows what the actual worker load was during those two. There are too many variables that were probably not controlled for.

**Comment by michaelklishin** [comment]
Submitted the above too soon. Monitoring the number of open connections will help prove my hypothesis. But if you have enough connections to consume 200-300 MB, your solution should not be heartbeat interval tweaking (like I said, don't use values like 2 and 2000 but 10 should be no different from 15 or 20). It should be

 * Using a memory profiler to find out what exactly consumes RAM
 * Possibly reducing [TCP buffer sizes](http://www.rabbitmq.com/networking.html) which can lower per connection RAM usage by an order of magnitude (with a comparable decrease in throughput).

**Comment by michaelbaudino** [comment]
Wow, thanks for all this info: I actually thought that the `heartbeat` config was in milliseconds 😥 

I'm currently tuning our applications, and it's looking great so far with Sneakers default value (30) 🚀
