### ISSUE TITLE
Recover from database failure?

### ISSUE THREAD

**Issue by w00lf** [jondot/sneakers#321]
Hello, i am currently working with version 2.6.0 to process messages from our services. In our system we have a cluster of PostgreSQL servers that live behind Haproxy balancer. All is working fine until current database server crashes for whatever reason. When this happens Haproxy switches to another server and database starts to work as normal, however, we start to receive constant thread of ```PG::ConnectionBad: PQsocket() can't get socket descriptor``` in our airbrake. It seems as worker stack in an event loop and cannot reconnect to a new server that Haproxy switched to. My question is: what is the graceful way of dealing with that kind of situations? I tried to simulate this situation on my computer and even with the simple connection to the database this also occurs. My current workaround is to call `Process.kill('TERM', Process.pid)` in worker to produce a new one but i think that it is a very clumsy way to do that.

**Comment by michaelklishin** [comment]
Database connectivity awareness is out of scope for Sneakers.
