### ISSUE TITLE
Is sneakers.io down?

### ISSUE THREAD

**Issue by jdickey** [jondot/sneakers#328]
My DNS says that there is no active `sneakers.io` domain, and Google Public DNS agrees:

```
$ nslookup sneakers.io 8.8.4.4
Server:		8.8.4.4
Address:	8.8.4.4#53

** server can't find sneakers.io: NXDOMAIN

$ nslookup sneakers.io 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find sneakers.io: NXDOMAIN

$
```

If it's gone permanently, the link should probably be removed from the  repo description.

**Comment by Tensho** [comment]
Confirm, it's down

**Comment by jondot** [comment]
Having a DNS issue, thanks for spotting it! Handling it now.

**Comment by jondot** [comment]
Back now. Thanks all for the swift report!
