### ISSUE TITLE
Sneakers 2.5.0 vs. 2.6.0 Error Handling

### ISSUE THREAD

**Issue by drews256** [jondot/sneakers#332]
So, I have hardly had any issues with Sneakers so far and I love it!

Today, I was spinning up a new Rails 5.1 application that is API only and started to try to get it set up with my Bigwig RabbitMQ service. I already have three separate rails applications that are consuming messages from this instance just fine. 

I ran bundle install and instead of Sneakers 2.5.0 it installed 2.6.0, fine, I like to keep my Gems up to date. 

The issue came when I started up the app. I use foreman to manage my workers and low and behold, not even an attempt to connect to my end point. Just 

```
15:18:17 task_workers.1            | 2017-11-16T23:18:17Z p-1677 t-oww72seug INFO: Worker 1 finished unexpectedly with status 1
15:18:17 task_workers.1            | 2017-11-16T23:18:17Z p-17860 t-oww72seug DEBUG: [worker-assigned_plan.task:1:q508fb][#<Thread:0x007fd8b687f050>][assigned_plan.task][#<Sneakers::Configuration:0x007fd8ba6e6050>] New worker: subscribing.
15:18:17 task_workers.1            | 2017-11-16T23:18:17Z p-17860 t-oww72seug DEBUG: Sent protocol preamble
15:18:17 task_workers.1            | Unexpected error Empty response received from the server.
15:18:17 task_workers.1            |   /Users/andrew/.rvm/gems/ruby-2.4.1@assigned-action-plans/gems/amq-protocol-2.2.0/lib/amq/protocol/frame.rb:60:in `decode_header'
15:18:17 task_workers.1            |   /Users/andrew/.rvm/gems/ruby-2.4.1@assigned-action-plans/gems/bunny-2.7.2/lib/bunny/transport.rb:237:in `read_next_frame'
15:18:17 task_workers.1            |   /Users/andrew/.rvm/gems/ruby-2.4.1@assigned-action-plans/gems/bunny-2.7.2/lib/bunny/session.rb:1127:in `init_connection'
15:18:17 task_workers.1            |   /Users/andrew/.rvm/gems/ruby-2.4.1@assigned-action-plans/gems/bunny-2.7.2/lib/bunny/session.rb:310:in `start'
``` 

over and over and over again. 

I did not expect it to connect immediately, but it didn't even try and my Rabbit MQ  instance doesn't even register an attempted connection. 

I have no global Sneakers configuration, and I use Bunny for connections.

My workers are of the format: 

```ruby
class ExampleWorker
    include Sneakers::Worker
    Sneakers.configure connection: Bunny.new(ENV['AMQP_PATH']),
      :exchange => 'worker_fanout',
      :exchange_type => :fanout
 
    from_queue 'some.appropriate.queue',
      exchange: 'worker_fanout',
      exchange_type: :fanout,
      durable: true,
      auto_delete: true
 
    def work(payload)
      do_something_important_here
    end
end

``` 

I was able to pull a separate app, upgrade to Sneakers to 2.6.0 and I saw the same effect when trying to run my app. 

If I go back down to 2.5.0 I see 

```
15:41:13 milestone_workers.1 | Unexpected error PRECONDITION_FAILED - cannot redeclare exchange 'worker_fanout' in vhost '0LA7Cc3WfJ-l' with different type, durable, internal or autodelete value
15:41:13 milestone_workers.1 |   /Users/andrew/.rvm/gems/ruby-2.4.1@tasks/gems/bunny-2.7.2/lib/bunny/channel.rb:1938:in `raise_if_continuation_resulted_in_a_channel_error!'
```

This is the expected result and in the RabbitMQ management UI I am able to see my connection, even though Sneakers is unsuccessful.

**Comment by drews256** [comment]
Hmm. Its a little concerning that its been 2 weeks since I have submitted this issue with no comment. Is sneakers on hold for dev work?

**Comment by michaelklishin** [comment]
> Unexpected error PRECONDITION_FAILED - cannot redeclare exchange 'worker_fanout' in vhost '0LA7Cc3WfJ-l' with different type, durable, internal or autodelete value

means different versions try to declare an exchange with different properties, which is a protocol-level channel exception. I don't immediately see anything in [2.6.0 release notes](https://github.com/jondot/sneakers/releases/tag/v2.6.0) that would potentially result in this. Taking a [traffic capture](https://www.rabbitmq.com/amqp-wireshark.html) would provide a lot of very valuable information in investigating this.

I'm not sure I understand the

> I have no global Sneakers configuration, and I use Bunny for connections.

part.

**Comment by drews256** [comment]
That error is completely expected and seen when I bring the sneakers version back down to 2.5.0. 

> I have no global Sneakers configuration, and I use Bunny for connections.

Just trying to say I have no sneakers.conf, and I configure Sneakers instances utilizing a Bunny instance like: 

```
     Sneakers.configure connection: Bunny.new(ENV['SOME_AMQP_PATH']),
       durable: true,
       exchange: 'some_fanout',
       exchange_type: :fanout,
       timeout_job_after: 30
 
    from_queue 'some.queue',
      exchange: 'some_fanout',
      exchange_type: :fanout,
      durable: true
```

I will work on the traffic capture soon.
