### ISSUE TITLE
Maxretry Handler: Base64 Payload & Properties

### ISSUE THREAD

**Issue by Tensho** [jondot/sneakers#337]
I wonder why does Sneakers [encode](https://github.com/jondot/sneakers/blob/master/lib/sneakers/handlers/maxretry.rb#L141) initial message payload and properties with Base64? It's not convenient to look at an encoded failed message in the RabbitMQ managament web console.  What is the reason for such decision? If I understand correctly, any client will pack somehow binary data with some transport encoding (Base64) anyway...

**Comment by Tensho** [comment]
@jondot, PING

**Comment by Tensho** [comment]
@jondot , Please could you answer this question?

**Comment by highander** [comment]
Even more I can't understand how can I move messages from error-queue back to queue.

Initially when messages are being retried their payload looks like this:
`{"hr_candidate_id":"1","asana_task_id":null,"env":"development"}`.

When such messages are placed into error-queue their payload changes to something like this:
`{"error":"reject","num_attempts":6,"failed_at":"2018-04-23T18:35:22+03:00","payload":"eyJocl9jYW5kaWRhdGVfaWQiOiIxIiwiYXNhbmFfdGFza19pZCI6bnVsbCwi\nZW52IjoiZGV2ZWxvcG1lbnQifQ==\n","properties":"cZWF0aC1==\n"}`

So moving such message back to queue does not have sense cause they have now absolutely another payload!

**Comment by Tensho** [comment]
Yeap, I have a special custom `Target1ErrorWorker`, `Target2ErrorWorker`, `Target3ErrorWorker` workers to compose initial messages from the error messages and re-publish them back to the target queue. That's why I proposed to consider [providing error info in a message metadata](https://github.com/jondot/sneakers/issues/350). This approach will allow easy to shovel error messages from the error queue to the target queue without any modification.
