### ISSUE TITLE
Cannot load rails secrets in workers

### ISSUE THREAD

**Issue by lclemence** [jondot/sneakers#342]
Apparently I need a connection config per worker otherwise it takes the default config.
So that is working but i cant load secrets from rails here...
```from_queue 'sync-rental', durable: true, amqp: '...'```
What is the work around?
Is there an example of setting the conf with runner_config_file

**Comment by michaelklishin** [comment]
I'm afraid that's not enough information to suggest much. I'm not a Rails user so I cannot how Sneakers can affect secret loading but we'd need to have some evidence (a reproducible example) of that.
