### ISSUE TITLE
Worker doesn't closes the connection

### ISSUE THREAD

**Issue by paulohtfs** [jondot/sneakers#344]
Hi everyone,
I'm having a problem with sneaker leaking connection with RabbitMQ. I look up and didn't find anything that resolve my problem (or at least every thing that I tried, didn't work).

When my rails application worker consumes a message from the queue, it creates a connection on rabbitmq, but after finishing and sending the ack, the connection still open. That's happens with every message.

My worker is basically this:
```ruby
class Worker
  include Sneakers:Worker

  from_queue 'test.queue',
                      retry_routing_key: 'test.queue'
                      arguments: { 'x-dead-letter-exchange': ENV['RETRY_EXCHANGE'] }

  def work(message)
    # do something
    ack!
  rescue => error
    reject!
  end
end
```

There is any settings to do close the connection after the worker finished?

**Comment by Spaceghost** [comment]
As of a411f05, https://github.com/jondot/sneakers/blob/a411f05d2e4a40ab2045b8f99aad6647ef4a30a5/lib/sneakers/worker.rb#L99-L106

**Comment by paulohtfs** [comment]
@Spaceghost thanks for the answer.

I still don't understand the relation between the PR and the `stop` method.
Where should I call `stop`?

**Comment by paulohtfs** [comment]
For more information. I'm running the task `sneakers:run` to create the workers.

**Comment by paulohtfs** [comment]
Nevermind...
In some point of my code, i used the Sneakers::Publish publish method, and the connection still opened.
Thanks and closing...

**Comment by Spaceghost** [comment]
I'm still looking for the PR you mentioned, would you mind dropping a link?

As for the use of `#stop`, I'd either suggest looking through the code at least, if not using it or writing your own using what you learn from it. Sorry I can't be much help at the moment, my loadavg is ridiculous these days.
