### ISSUE TITLE
Keep Error Information As Message Metadata

### ISSUE THREAD

**Issue by Tensho** [jondot/sneakers#350]
I wonder why does MaxRetry handler change a message payload to reflect error details? RMQ (AMQP) message has a bunch of metadata fields, including custom headers, that could be used to store error type, timestamp, backtrace, etc. With initial (unchanged) message payload, it's much easier to shovel from error queue to the target queue after bugfix.

This question crosses ["Maxretry Handler: Base64 Payload & Properties"](#337) issue.

**Comment by michaelklishin** [comment]
I don't think it would make a lot of difference if we switched to headers. That's the solution the original author arrived at and there's nothing wrong with it in most cases.

We can switch but it would be a breaking change.

**Comment by Tensho** [comment]
We may introduce a feature toggle which will change the place of the error metadata:

- payload
- headers

and set the current one as a default.

As for difference, I have a separate dead message (error) worker which decodes a message, retrieves initial pauload, republishes it to the target queue. I run it after the bug is fixed to reprocess dead messages again. With the option of storing error metadata in headers I would be able just use RMQ shovel.

I wonder maybe @jondot experienced some issues with the headers approach I may skip... 🤔

**Comment by eetay** [comment]
@Tensho we're facing same problem as well, and yes, we'd like to use shovel but can't. do you mind sharing your 'restore-original-message' code?

**Comment by Tensho** [comment]
@eetay Yep, kind of that:
```
class AbcErrorWorker
  include Sneakers::Worker

  from_queue "abc-error", durable: true,
                          ack: true,
                          prefetch: 1,
                          threads: 1

  def work_with_params(payload, delivery_info, metadata)
    parsed_payload = JSON.parse(payload)
    
    initial_payload = Base64.decode64(parsed_payload["payload"])
    
    exchange.publish(initial_payload, routing_key: delivery_info[:routing_key], content_type: 'application/json')

    ack!
  end

  def exchange
    @exchange ||= begin
      x = channel.topic('errors-transit', durable: true)
      q = channel.queue("abc",
        durable: true,
        arguments: {
          'x-dead-letter-exchange': "abc-retry"
        })
      q.bind(x, routing_key: "the-same")
      x
    end
  end

  def channel
    @channel ||= connection.create_channel.tap(&:confirm_select)
  end

  def connection
    @connection ||= Bunny.new.start
  end
end
```

**Comment by eetay** [comment]
Thanks!
Just FYI - I did manage to modify the "Sneakers::Handlers::Maxretries" and created a tiny gem with the modified retry handler which uses a custom header to describe the retries and errors: https://rubygems.org/gems/sneakers-retry
and I am able to use 'shovel' to re-queue messages after all retries failed

use like so:
```
class MyWorker
   from_queue 'audit_service', {
      handler: SneakersRetry::Handlers::Maxretry2,
      ...
   }
   ...
end
```

Eetay

**Comment by Tensho** [comment]
Yeah, I also think about custom handler in the current project, but would like first to understand initial `MaxRetry` author intention...
