### ISSUE TITLE
Upgrading from v1.1.2

### ISSUE THREAD

**Issue by florrain** [jondot/sneakers#360]
Hi there,

I'm working with an application that is using an old version of Sneakers and would like to know what are the guidelines to bump the version up to the latest possible. 

I don't see an upgrading doc nor notes in the readme so it makes me think that there aren't that many breaking changes but I'd like to check with maintainers or people that upgraded.

Thanks!

**Comment by michaelklishin** [comment]
[There is a change log](https://github.com/jondot/sneakers/blob/master/ChangeLog.md).
