### ISSUE TITLE
Release 2.12.0

### ISSUE THREAD

**Issue by yosiat** [jondot/sneakers#367]
When do you plan to release a version with bunny 2.11.0 support?

I see there is already commit to master

**Comment by Tensho** [comment]
@michaelklishin Could you please release the most fresh `sneakers` version to rubygems? I'm keen in Timeout reduction either.

**Comment by michaelklishin** [comment]
@Tensho I no longer read every GitHub notification except for the RabbitMQ org, so a better way to ask is to do it on [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Let's eye a new release early next week.

**Comment by Tensho** [comment]
@michaelklishin Thank you 🙇

**Comment by michaelklishin** [comment]
FTR, I haven't forgotten about this.

**Comment by Tensho** [comment]
God bless you, Michael ^_^

**Comment by michaelklishin** [comment]
I've produced an RC, `2.12.0.rc1` with a couple more PRs. Please give it a shot. We'll take a few days to update the change log.

**Comment by seenivasanpalanisamy** [comment]
@michaelklishin Can we use **2.12.0.rc1** this release in production?  When can we expect official release for **v-2.12**

**Comment by gabrieljoelc** [comment]
@seenivasanpalanisamy have you tested out `2.12.rc1` at all? looks like there have been 355 downloads of that version. I'm not sure what our metric is for sneaker RC's. 😅 

![image](https://user-images.githubusercontent.com/147849/62487175-09cd8a80-b776-11e9-92f7-39ee54c0e18e.png)

any opinions anyone?

**Comment by seenivasanpalanisamy** [comment]
@gabrieljoelc we didn't done any kind of rigorous testing. We need a feature in this version!! Adding **middleware**, which we tested :)

**Comment by estolfo** [comment]
Hi, we are looking forward to a `2.12.0` release! We have [a PR open](https://github.com/elastic/apm-agent-ruby/pull/599) against the Elastic APM Agent with support for Sneakers but it depends on some functionality of the upcoming v2.12.0. Do you have an estimate as to when it will be released? Thanks!

**Comment by gabrieljoelc** [comment]
sorry for the delay folks. I will get to this during my holiday break. _goes to make a slack reminder_

**Comment by estolfo** [comment]
Super, thanks for the update, @gabrieljoelc

**Comment by gabrieljoelc** [comment]
Release `v2.12.0` pushed to rubygems https://rubygems.org/gems/sneakers/versions/2.12.0.
