### ISSUE TITLE
sneakers.pid file does not get generated

### ISSUE THREAD

**Issue by cdavaz** [jondot/sneakers#370]
So I can set "pid_path" and see that it gets set correctly from the sneakers startup output:
```
Workers ....: Worker::Transcribe
Log ........: log/sneakers.development.log
PID ........: /tmp/sneakers.pid

                               Process control
================================================================================
Stop (nicely) ..............: kill -SIGTERM `cat /tmp/sneakers.pid`
Stop (immediate) ...........: kill -SIGQUIT `cat /tmp/sneakers.pid`
Restart (nicely) ...........: kill -SIGUSR1 `cat /tmp/sneakers.pid`
Restart (immediate) ........: kill -SIGHUP `cat /tmp/sneakers.pid`
Reconfigure ................: kill -SIGUSR2 `cat /tmp/sneakers.pid`
Scale workers ..............: reconfigure, then restart
================================================================================
```

but this file doesn't actually get created. Neither did it get created when pid_path defaulted to just "sneakers.pid" in the current directory. I've experienced this on two different systems (one OS X, the other CentOS). Anything else I could be doing wrong?

**Comment by daveboling** [comment]
@cdavaz I'm also running into this issue. Any chance you figured out what needed done? I can only get the pid file to be generated when I let it self-daemonize via configuration, but it doesn't treat this pid as a master process for use with a process manager. I'm trying to make it work with monit. I can get monit to run sneakers, but due to the missing pid file, it will constantly fail and being doubling up sneaker processes.

I've everything in this issue to no avail: https://github.com/jondot/sneakers/issues/59

**Comment by cdavaz** [comment]
@daveboling, I haven't played around with the self-daemonize feature but what I did do was get the PID in a script:
`#!/usr/bin/env bash
rm -rf /tmp/foreman/job/*
nohup sneakers work Worker::Transcribe --require lib/foreman.rb >> /tmp/sneakers.log 2>> /tmp/sneakers.err < /dev/null &
echo $! > /tmp/sneakers.pid
`
Sending a SIGTERM to this pid seems to work fine.

**Comment by daveboling** [comment]
@cdavaz Thank you, that really helped. Also, I'm curious. Do you run all of your workers individually like that?

For anyone using monit for this, I ended up doing something close to that but using the `sneakers:run` in the foreground as a master process.

e.g.
```
/bin/bash -c 'cd /var/my_rails_service && (RAILS_ENV=integration WORKERS=PropertyWorker,UserWorker nohup bundle exec rails sneakers:run &>/tmp/sneakers_monit.out & echo $!>/tmp/pids/sneakers.pid)'
```

I've seen scattered topics here and there on how to run sneakers in production, so I can't say for sure if this is recommended.

**Comment by michaelklishin** [comment]
Sounds like #334 is the actionable part here, the rest is just a discussion => closing.
