### ISSUE TITLE
there is no Gemfile.lock, but Dockerfile presumes it exists

### ISSUE THREAD

**Issue by gorodulin** [jondot/sneakers#371]
Hi!

Seems like `Dockerfile` is useless, bc build fails with
`Step 9/12 : COPY Gemfile.lock /sneakers/Gemfile.lock
ERROR: Service 'sneakers' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder541788757/Gemfile.lock: no such file or directory`

Probably, I'm the only person here who doesn't plan to run `bundle install` locally after gitcloning. :)
Please update Dockerfile, it should work oob.

Thanks!

**Comment by Tensho** [comment]
Hi, fixed in #375.
