### ISSUE TITLE
Scheduled Jobs

### ISSUE THREAD

**Issue by shaqq** [jondot/sneakers#380]
Hello!

I was wondering if Sneakers supports scheduled jobs via delayed queues, or plans to do so.

**Comment by lucaong** [comment]
Sneakers does not support it out of the box, but it's not too hard to do that, with a RabbitMQ plugin. You can my blog post about it, if that helps: [delayed jobs with Rails and RabbitMQ](https://lucaongaro.eu/blog/2018/07/31/delayed-jobs-with-rails-and-rabbitmq.html)

**Comment by rept** [comment]
@lucaong I've used your blog as a guideline and can confirm it works perfectly!

**Comment by gabrieljoelc** [comment]
Thanks for the feature request @shaqq and the suggestion @lucaong.

Another option is using in combination with sidekiq (requires Redis as well) which does have this out of the box.

I don't think we'll support this out of the box right now so closing.
