### ISSUE TITLE
is Redis Required?

### ISSUE THREAD

**Issue by aronlmin** [jondot/sneakers#383]
This is a really lame question and can be immediately closed when answered, but I am absolutely a newbie and just barely got a hello world functionality working with sidekiq (I have several apps running on a single Ec2 and without paying an arm and a leg i cannot spin up another sidekiq / redis instance and therefore am forced to look at Sneakers + RabbitMQ), so my knowledge of background processing is very small.

If I understand correctly RabbitMQ is a competing product to Redis (i know they tackle two different sets of problems though), Redis is a key-value store with some messaging capabilities. Is sneakers reliant on Redis for its functionality in addition to RabbitMQ? or does it function as a standalone? Maybe the doc examples can explain a little further why Redis is mentioned.

**Comment by michaelklishin** [comment]
Redis is a [development dependency](https://github.com/jondot/sneakers/blob/e2b7b2ab888567910310a275f6b0e5d95474ed55/sneakers.gemspec#L27) that's used in integration tests (even there it is optional, as in, some tests should be skipped if Redis is not running locally).

Some features of Sneakers can be built on top of Redis messaging, others cannot (that I know of, I obviously know significantly more about RabbitMQ capabilities and protocols than modern Redis).

**Comment by michaelklishin** [comment]
[This wiki page](https://github.com/jondot/sneakers/wiki/Why-i-built-it) is about 5 years old but explains certain design decisions and rationale behind Sneakers. HTH :)

**Comment by bonyiii** [comment]
I know this is an old question, but my understanding is that  number of jobs which needs to be run in the test suit is stored in redis and then it is checked if that many jobs were run already:

https://github.com/jondot/sneakers/blob/9780692624c666b6db8266d2d5710f709cb0f2e2/spec/sneakers/integration_spec.rb#L68

and the value is redis is incremented by the workers here: https://github.com/jondot/sneakers/blob/9780692624c666b6db8266d2d5710f709cb0f2e2/spec/fixtures/integration_worker.rb#L14

I assume this is to keep a simple way to communicate among multiple processes?
