### ISSUE TITLE
Documentation Request - Referencing Workers from Ruby Grape Routes

### ISSUE THREAD

**Issue by alilland** [jondot/sneakers#384]
All bases seem covered for Sinatra, Rails and Rake, but examples for triggering background tasks from [Grape](https://github.com/ruby-grape/grape) Routes are not there, wish I could issue a pull request but I am absolutely lost in the weeds =/

**Comment by aronlmin** [comment]
Looks like i have it working, i will post something in a few days

**Comment by michaelklishin** [comment]
Thank you.

**Comment by aronlmin** [comment]
here is a sample grape project using Sneakers + Bunny
[Grape Sneaker Example API](https://github.com/aronlmin/grape-sneaker-example)

**Comment by gabrieljoelc** [comment]
Wanna add this to the wiki or pull request the readme and then we can close this issue?
