### ISSUE TITLE
Handling Protobuf payload with ContentType handler

### ISSUE THREAD

**Issue by qnm** [jondot/sneakers#385]
Hi,

I'm looking for a little advice, perhaps what I'd like to do isn't possible in the current implementation of Sneakers.

I need to decode a Protobuf payload coming via RabbitMQ message.

I have a working implementation using `work_with_params` however I'd dearly love to move my marshalling code into a `ContentType` handler.

Because Protobuf is not self-describing, additional metadata must be provided to unserialize to the correct object type. The system I am interfacing with uses AMQP `params` metadata to provide this data.

However, I don't appear to be able to access anything other than `payload` when using a `ContentType` handler.

Is there a way to standardise marshalling when headers or params are also required?

Thanks in advance.

**Comment by michaelklishin** [comment]
Your findings are correct, [this interface](https://github.com/jondot/sneakers/blob/master/lib/sneakers/content_type.rb) considers that the payload is all that's necessary.

You are welcome to contribute a PR for `2.13.0` (`2.12.0` is the current development cycle). Thank you.
