### ISSUE TITLE
Jobs stuck issue

### ISSUE THREAD

**Issue by TarasBardiuk** [jondot/sneakers#392]
Hello.

I'm using Sneakers on a quite big platform (hundreds of jobs per hour) and faced with very confusing problem.
After some time of work, the queues seem to "freeze" and don't complete any pushed job. But if I restart the Sneakers, all "stuck" jobs are executed immediately.

I assume that the problem may lie in the fact that when performing jobs, the exception "Sneakers::WorkerTimeout: execution expired" occurs quite often.
The exception itself is not critical at the current stage of development, but, I suppose, it causes all workers to freeze until a full restart.

Is there any solution? Thank you in advance.

**Comment by Deivisson** [comment]
I get the same issue !

**Comment by TarasBardiuk** [comment]
@Deivisson, what version of the gem are you using?

I found that in the most [recent release](https://github.com/jondot/sneakers/releases/tag/v2.11.0), the problem with freezing workers was fixed. The preconditions for that fixed issue were slightly different, but the fact of "freezing" is the same.

I used a fairly old version 2.6.0, so I updated the gem and for now everything looks good. So I'll wait a few days and let you know about the result.

**Comment by Deivisson** [comment]
@TarasBardiuki was already using the latest version. But in few days when i return to the project, i discovery a problem in my code related with connection pool size, so i found solutions to increase the pool size in favor my workers and the problema look be resolved now. Already working in 2 days without freeze. If keep so, soon be in production :-)

thks for the feedback

**Comment by michaelklishin** [comment]
Thanks for following up back to the list. Bunny needs some metrics around worker pool size/activity.

**Comment by luismiv85** [comment]
> @TarasBardiuki was already using the latest version. But in few days when i return to the project, i discovery a problem in my code related with connection pool size, so i found solutions to increase the pool size in favor my workers and the problema look be resolved now. Already working in 2 days without freeze. If keep so, soon be in production :-)
> 
> thks for the feedback

Hi @Deivisson , thanks for you response. Could yo please show me how you solve this? You increased a pool size where?

Thanks so much!
