### ISSUE TITLE
rake sneakers:run fails on Rails 6, new default code loader related issue.

### ISSUE THREAD

**Issue by gaotongfei** [jondot/sneakers#396]
When running `rake sneakers:run` on Rails 5 application without specify `WORKERS` environment variable, sneakers will look for the `Sneakers::Worker::Classes`, which is appended when include `Sneakers::Worker` in class.

This works on Rails 5 app. However, Rails 6 changed its default code loader to zeitwerk, running sneakers rake task won't load workers class.

![sneakers-run](https://user-images.githubusercontent.com/7582133/60479787-95f11b80-9cb9-11e9-9564-1d13a6ba8267.png)

This can be fixed by adding
```
::Zeitwerk::Loader.eager_load_all if defined?(::Zeitwerk)
```
in `lib/sneakers/tasks.rb` file.

Any thought? Would a PR be welcomed?

**Comment by gabrieljoelc** [comment]
Yes thank you for letting us know. A backwards compatible PR would be very welcome. 😄
