### ISSUE TITLE
Possible wrong log level in reload_config!

### ISSUE THREAD

**Issue by melvinsh** [jondot/sneakers#400]
Every time I start my environment with log level `WARN` I get the following message from all of my workers:

```
WARN: Loading runner configuration...
```

This seems to be defined here: https://github.com/jondot/sneakers/blob/7c059d1490e4dde43f98b801c38e4e0df7ac458c/lib/sneakers/runner.rb#L43

Shouldn't this be `Sneakers.logger.info` as it is not an actionable warning?

**Comment by melvinsh** [comment]
@gabrieljoelc what do you think? I'd be happy to submit a PR.

**Comment by gabrieljoelc** [comment]
yes it should and yes please do! 🙏

**Comment by melvinsh** [comment]
Thanks @gabrieljoelc & @michaelklishin 😊👏
