### ISSUE TITLE
Bunny client properties

### ISSUE THREAD

**Issue by ac-dc87** [jondot/sneakers#410]
Is there a way to override or append to bunny client properties?

<img width="906" alt="Screen Shot 2019-10-10 at 11 34 03 AM" src="https://user-images.githubusercontent.com/37820788/66584298-daab0f00-eb52-11e9-9bd9-c43a712ceb19.png">

**Comment by iagopiimenta** [comment]
try this: 
```ruby
Sneakers.configure(
  properties: {
    connection_name: 'test'
  }
)
```
