### ISSUE TITLE
Ability to connect to multiple vhosts

### ISSUE THREAD

**Issue by middletoni** [jondot/sneakers#445]
Is there a way within Sneakers to have 2 configurations, with certain workers processing certain vhosts?  My current build uses rails, and has a 'secure' and a 'open' vhost, but I see no way to define within a worker which connection/vhost to use.

**Comment by michaelklishin** [comment]
This is a not a scenario Sneakers or most such frameworks optimize for. You can override connection options in a custom Rake task or similar.
