### ISSUE TITLE
[Question] Hot reload of code

### ISSUE THREAD

**Issue by jlntrt** [jondot/sneakers#447]
Hey there,

I'm working on a ruby on rails app that uses sneakers. Within a worker I use several classes that are located in the app folder which should automatically reloaded after the code changes but don't for any reason. 

I searched for some information about this in the wiki but found nothing. 

Can anyone of you give me a tip what I can do to not restart my docker stack for every code change in development?

Thank you! :)

**Comment by michaelklishin** [comment]
One option would be [running with Guard or similar](https://auth0.com/blog/ruby-on-rails-killer-workflow-with-docker-part-1/). I haven't tried it if there is a solution that works for Ruby processes that can fork, it should work for Sneakers.
