### ISSUE TITLE
Is there some potential  issues if setting single worker but multi-thread in prd env?

### ISSUE THREAD

**Issue by TDtianzhenjiu** [jondot/sneakers#461]
As the title described
I found multi-process take too much mem

**In general, multi-process improves the system’s reliability, in order to save mem I want to set single worker and multi-thread, it also consumes and processes MQ message parallelly.** 

But I'm not sure whether single workers will cause other issues?

**Comment by michaelklishin** [comment]
@jondot can we enabled Discussions for this repo so that we can convert issues that are questions to discussions?
