### ISSUE TITLE
Ruby 3.2.0 File#exists?

### ISSUE THREAD

**Issue by wwwermishel** [jondot/sneakers#468]
Methods 'exists?'  for class File was removed in ruby 3.0.0 => https://bugs.ruby-lang.org/issues/17391
Could you please change method 'exists?' on 'exist?' here => https://github.com/jondot/sneakers/blob/31d0cb25dc5bbcfb0749567e9e0f80e6353fb66b/lib/sneakers/spawner.rb#L9
In Ruby 2.*.* we also hav method 'esixt?' for File.

**Comment by michaelklishin** [comment]
You are welcome to submit a PR.
