### ISSUE TITLE
Support correlating multiple tasks into a batch

### ISSUE THREAD

**Issue by nathanpalmer** [jondot/sneakers#48]
We often run into situations where multiple jobs are executed and we need to do something upon completion of all tasks. These could be multiple of the same task or mixed. Is this something that is supported or on the horizon?

**Comment by jondot** [comment]
Thanks for the input, closing and moving this to roadmap discussions with the core team, under 'batch / distributed coordination'.

**Comment by nathanpalmer** [comment]
@jondot Is that happening in the open here on Github or somewhere else?

**Comment by jondot** [comment]
My hope is that everything is transparent of course. I'm just in the process of noting down important issues, discussions, requirement etc.
