### ISSUE TITLE
Using with God or Runit

### ISSUE THREAD

**Issue by simonmorley** [jondot/sneakers#59]
I've push moved a big project over from Hutch to Sneakers. Happier days are ahead I can see :) This is a much lighter and more flexible project.

All is well, however, we are struggling to get things to pay nice with either runit or god.

God in particular seems unfriendly, I'm not sure why. 

I've created a god config. file as so:

```
God.watch do |w|
  w.name = "sneakers"
  w.dir = "/var/www/html/cucumbertony/production/current/"
  w.start = "RAILS_ENV=production bundle exec WORKERS=MyWorkers,AnotherWorker rake sneakers:run"
  w.keepalive
end
```

It looks like it starts and I can see the connections in RabbitMQ. But on closer inspection, I can see it's exiting and a new pid is created.

I've tried to force a pid_file in the sneakers config AND the god config but this doesn't help either.

The god log shows the following over and over and over and over.

```
I [2014-07-29 23:19:39]  INFO: sneakers moved 'up' to 'up'
I [2014-07-29 23:19:44]  INFO: sneakers [trigger] process is not running (ProcessRunning)
I [2014-07-29 23:19:44]  INFO: sneakers move 'up' to 'start'
```

Can you suggest something I should  / could do to facilitate running this with god?

**Comment by rud** [comment]
Think it is safe to close as no more information about the issue seems to be arriving.

**Comment by jondot** [comment]
Closing for cleanups :)
