### ISSUE TITLE
Publishing tasks?

### ISSUE THREAD

**Issue by glenjamin** [jondot/sneakers#6]
I'm not sure if I'm just being dense here, but I can't seem to see any docs or examples of publishing messages into Rabbit, only worker docs.

Are publishers outside the scope of sneakers?

**Comment by sharshenov** [comment]
I am also getting UNEXPECTED_FRAME errors. Can you share your solutions?

**Comment by maxigs** [comment]
I'm just opening up a new channel in each task that i process (lazy, only when its required to publish), since those are usually bigger tasks it works ok.

If you have a higher load you might want to think about moving the publishing into the manager to have one permanent channel, but thats a lot more complex.

**Comment by sharshenov** [comment]
I got rid of UNEXPECTED_FRAME errors by modifying my worker that way:
```ruby
class MyWorker
  include Sneakers::Worker

  from_queue :test

  def work msg
    params = JSON.parse msg, symbolize_names: true

    result = MyJobProcessor.new(params).result

    publisher.publish result, to_queue: :test_callback

    ack!
  end

  def publisher
    @publisher ||= Sneakers::Publisher.new
  end
end
```

@jondot how do you think? Should I create PR for replacing Sneakers::Worker#publish method with this two methods:
```ruby
def publish *attrs
  publisher.publish *attrs
end

def publisher
   @publisher ||= Sneakers::Publisher.new
end
```

**Comment by jondot** [comment]
@sharshenov I see what you did there, I think it's smart. However please notice that on first look, you're localizing a publisher instance per process and on second look - since a worker is instantiated per message, you're also instantiating a new `Publisher` instance per message. It would be the same as doing

```
Sneakers::Publisher.new.publish(...)
```
in the `#work` body. 
Is that what you need?

**Comment by sharshenov** [comment]
Oh. Now I see, that my workaround is an overhead.
I'll implement manager as @maxigs suggested.
Thank you!

**Comment by jondot** [comment]
Thanks guys, closing for cleanups :)

**Comment by gabrieljoelc** [comment]
As an aside, we use [`connection_pool`](https://github.com/mperham/connection_pool) to manage our bunny connections in [`la_gear`](https://github.com/giftcardzen/la_gear) but we actually do it at the publisher level (see [here](https://github.com/giftcardzen/la_gear/blob/master/lib/la_gear/bus.rb#L3-L13):
```ruby
    def init_pool(size = ::Sidekiq.options[:concurrency],
                       timeout = 3)
      $publisher = ConnectionPool.new(
        size: size,
        timeout: timeout
      ) { ::LaGear::Publisher.new }

      $publisher.with do |bus|
        fail 'Bus is lost!' unless bus.is_a?(LaGear::Publisher)
      end
    end
```
where `LaGear::Publisher` is a subtype of `Sneakers::Publisher`. We push messages through our abstraction into a Sidekiq/Redis "outbox" which then actually [publishes](https://github.com/giftcardzen/la_gear/blob/master/lib/la_gear/bus.rb#L74-L85) the message:
```ruby
$publisher.with do |publisher|
  publisher.publish(msg, opts)
end
```

**Comment by mtowers** [comment]
We're seeing a similar issue with sneakers `2.2.1`.  However, I'm not clear on why threading would be an issue in our scenario.  We pass `:threads => 1` and `:workers => 10` to `Sneakers.configure`.  And we're using [our own publisher implementation](https://github.com/RealSelf/stream-ruby/blob/master/lib/realself/stream/publisher.rb), which is instantiated at startup time and stored as an instance variable in a [worker class implementation (`ActivityWorker`)](https://github.com/RealSelf/stream-ruby/blob/master/lib/realself/daemon/activity_worker.rb).  See also [worker module (`Worker::@handler_params`)](https://github.com/RealSelf/stream-ruby/blob/master/lib/realself/daemon/activity_worker.rb)

Any ideas?

**Comment by jesmith17** [comment]
So there is a ton of conversation here, but still no examples of how to actually publish a message, especially when doing so outside of a worker. 
I plan on using Sneakers to invoke background jobs as the AMQP allows easy ways for systems outside of Ruby to publish messages. But in many cases I need to publish them myself. 

I agree with the points about the flexible formats, but it would be nice to at least have an example of how to use the publisher to actually send a message from outside a worker. That's not documented anywhere and beings reading the code hasn't proved useful to me to figure it out, I am struggling with how to stay with Sneakers for this as opposed to switching to a different gem. 

Can we just get a simple example of sending a message to Rabbit that a different worker can pickup and work on? You can omit the worker part, but something show how to define the exchange that you are publishing to would be helpful.

**Comment by maxigs** [comment]
You could also just use a different library to send messages into RabbitMQ, for queues to which sneakers is subscribed to.

I used the `bunny` or `amqp` gem for that, depending on the type of process. This triggered my initial job, and from the `sneakers` takes over with processing everything.

Publishing from within sneakers should already be mentioned above. I currently don't have any active project using it anymore, so i don't have a direct example to share at hand at the moment :(

**Comment by jesmith17** [comment]
The only examples of publishing within sneakers were related to  publishing from within a worker. But it's not clear how to actually invoke any of that from outside the worker. Especially when the worker config only uses the queue, and doesn't define the exchange (which is critical for publishing).

**Comment by mtowers** [comment]
We ended up following the `ConnetionPool` pattern described here where the pool contains instances of our custom publisher implementation.  The connection pool and publisher instances are initialized in our daemon startup script, with one publisher instance per worker thread.  We also have the name of our exchange available at that time as we're also using it for worker configs.

**Comment by maxigs** [comment]
@jesmith17 Do you really have a case where you need to publish from outside a worker but still within sneakers processes?

If yes, you could still follow the way i describe and use AMQP directly to publish a message going into a sneakers queue. Not really the best way, but straight forward to use.
