### ISSUE TITLE
Does it have ssl support?

### ISSUE THREAD

**Issue by anhuiliujun** [jondot/sneakers#63]

**Comment by andreisav** [comment]
Awesome gem, but same issue here. 
queue::subscribe limits the options that are being passed to Bunny. 
    @bunny = Bunny.new(@opts[:amqp], :vhost => @opts[:vhost], :heartbeat => @opts[:heartbeat], :logger => Sneakers::logger)

Would be great to be able to pass  :tls_cert, :tls_key,   :tls_ca_certificates and  :verify_peer using the published gem.

**Comment by michaelklishin** [comment]
Or just an actual `Bunny::Session` you instantiate however you like.

**Comment by dbyron0** [comment]
+1 here.  Has anyone made any progress towards this?  I'll give it a whirl otherwise.

**Comment by andreisav** [comment]
it's in my backlog for sure, but no idea when I can get down to it. Please do give it a shot. Much appreciated.

**Comment by dbyron0** [comment]
https://github.com/jondot/sneakers/pull/124

**Comment by dbyron0** [comment]
Anyone have a minute to look at this pull request: https://github.com/jondot/sneakers/pull/124 ?

**Comment by jondot** [comment]
Closing.
