### ISSUE TITLE
evaluate `bunny_mock` in tests

### ISSUE THREAD

**Issue by jondot** [jondot/sneakers#64]
Evaluate if there's a need for https://github.com/primedia/bunny_mock in dirty tests.

**Comment by rud** [comment]
For "dirty tests" involving RabbitMQ in the past I've created some low-level helpers implemented using Bunny:
* `pop_entire_queue(queue_name)` - returns an array of what's on a queue; also practical for ensuring a clean state before a specific test.
* `expect_messages_received(queue_name, required_messages, timeout: 10.seconds)` - given an explicit list of messages expected to be found on the specific queue, wait a while to receive them. Any non-matching messages are ignored.
* `expect_matching_messages(queue_name, required_match_count, timeout: 10.seconds, &block)` -where the block is called for each message seen, success means `required_match_count` matches are found.
* finally, `create_message_on(queue_name, payload_hash)` to drop a message on a specific queue to trigger a consumer handling it.

Don't know if those building blocks would at all apply to implementing tests that interact with a live RabbitMQ instance.

**Comment by jondot** [comment]
Moving this to roadmap discussions under 'testing'.
