### ISSUE TITLE
how to re-establish database connection?

### ISSUE THREAD

**Issue by trungpham** [jondot/sneakers#67]
how do we reestablish ActiveRecord database connection after forking the worker process?

**Comment by harmoney-justins** [comment]
@clwang did the conifg above help, im getting the same

**Comment by clwang** [comment]
@harmoney-justins - Yes, I took out the reaping frequency. The way I tested this before go to production was increasing the thread count.

**Comment by abepetrillo** [comment]
Can someone explain how the reaping frequency can cause the `ERROR: [FAILED] could not obtain a database connection within 5 seconds (waited 5.000338 seconds).` ?
