### ISSUE TITLE
ack! method usage is confusing

### ISSUE THREAD

**Issue by adamniedzielski** [jondot/sneakers#74]
```ack!``` is just an alias to ```:ack``` as per https://github.com/jondot/sneakers/blob/master/lib/sneakers/worker.rb#L33

However, by Ruby conventions, I would expect bang method to do something rather than return something. Currently ```ack!``` call has to be placed at the very end of ```work``` method so ```:ack``` is returned from ```work```. This is quite implicit assumption which is present in all examples, but I could not find anything in the documentation about it.

This confused me, as I was trying to log something after ```ack!``` call and messages was not acknowledged.

This issue can be fixed in two different ways:
a) changing implementation of ```ack!``` (and ```reject!```, ```requeue!```) to setting a variable instead of returning value
b) improving the docs

I think it's worth discussing.

**Comment by jondot** [comment]
Closing and documenting this for roadmap discussions

**Comment by beyondcompute** [comment]
People are still burning on this after all this years. Maybe it’s time to re-work the `ack!` method so that its call at any place has the desired effect?

(Thanks to Sneakers contributors for their efforts!)

**Comment by dlibanori** [comment]
up
