### ISSUE TITLE
separate connections for sending vs. receiving message

### ISSUE THREAD

**Issue by trungpham** [jondot/sneakers#76]
See: http://bigwig.io/docs/message_throughput/

Can we have a separate connection for sending job, and a separate connection for receiving job?
Right now, we only one config called RABBITMQ_URL.
Perhaps, break it up into RABBITMQ_RX_URL, and RABBITMQ_TX_URL.

**Comment by jondot** [comment]
Closing and moving to roadmap discussion under 'publishing'
