### ISSUE TITLE
self-daemonization is depricated

### ISSUE THREAD

**Issue by maxstepanov** [jondot/sneakers#83]
It's news to me that self-demonization is now considered a bad practice.
I think it should be left in for people that want to use it.
Can author elaborate why it is depricated and marked for removal?

**Comment by rud** [comment]
It's duplicate behavior implemented better elsewhere. By relying on OS-provided demonization you can use the same management tools and monitoring you use for other services. Does that make sense?

**Comment by jondot** [comment]
Thanks @rud, that's a great formulation, I'll use it in my own explanation (I find this topic comes up once in a while in other areas as well).

**Comment by rud** [comment]
Glad I could help
