### ISSUE TITLE
Sneakers seems not to respect the vhost parameter from the amqp_url

### ISSUE THREAD

**Issue by niwo** [jondot/sneakers#89]
Hi,

I had an issue where the vhost parameter from the amqp_url was not respected.

As example for the amqp_url "amqp://user:password@rabbitmq-host:5672/%2fvhost"
Sneakers would set the vhost to the default value of "/" instead of "/vhost".

Only setting the vhost option explicitly to "/vhost" solved the issue.

Thanks,
Nik

**Comment by niwo** [comment]
As additional information: 

Using Bunny directly works just fine.
Bunny.new with the amqp_url from above takes the correct vhost value: 
```ruby
amqp_url = "amqp://user:password@rabbitmq-host:5672/%2fvhost"
puts Bunny.new(amqp_url)
#<Bunny::Session:9793120 user@rabbitmq-host:5672, vhost=/vhost, hosts=[rabbitmq-host]>
```
I would except the same behavior from Sneakers.

**Comment by polmiro** [comment]
Duplicate from #43. Just manually parse the url and set the vhost. Make sure you have an initial slash on the vhost name.

**Comment by arrtchiu** [comment]
I believe this is a different issue to #43. #43 is about sneakers ignoring an explicit `vhost` param. This is about sneakers not parsing the vhost out of the url correctly. Thankfully @niwo already found a workaround :)

The vhost is in the amqp url and should be parsed correctly. Bunny does parse it correctly.

**To reproduce**:  `Sneakers.configure amqp: 'amqp://user:password@host:5672/myvhost'`

**Expected**:  Sneakers connects to vhost `'myvhost'`

**Actual**:  Sneakers connects to vhost `''`

**Workaround**:  Explicitly set the vhost like this: `Sneakers.configure amqp: 'amqp://user:password@host:5672/myvhost', vhost: 'myvhost'`

Will fix and submit PR hopefully soon.

**Comment by jondot** [comment]
@arrtchiu I'm guessing the problem is around here? https://github.com/jondot/sneakers/blob/64e79bda391f9e9ac9e69944c8249e3552acaddf/lib/sneakers/configuration.rb#L39

**Comment by arrtchiu** [comment]
@jondot Yeah, I think that's the issue - we're setting the `:vhost` key in the `clear` method but not overwriting it later in `merge` which gets called during `Sneakers.configure`. Haven't yet had enough time to verify and patch myself though unfortunately.

**Comment by arrtchiu** [comment]
Made a dirty patch that works, but it's a super ugly solution. Have some ideas for something cleaner but want to make sure it won't affect any changes others might be making (don't we all hate merge-conflicts?) -- @jondot would that be a problem?

**Comment by jondot** [comment]
I think you can submit a PR, we'll work together to see how to merge it :)

**Comment by jondot** [comment]
@arrtchiu let me know if you need any help :)

**Comment by arrtchiu** [comment]
Hey @jondot, sorry to drop the ball like this but I ended up needing to switch away from Sneakers due to some legacy code on my part. I'll keep this discussion on-topic by opening another issue.

**Comment by abezzub** [comment]
I need this for my project, I just submitted a PR

**Comment by a0s** [comment]
Hi! I am using Sneakers 2.11.0, and I am not sure that this behavior is good:
```
2.7.1 :005 > AMQ::Settings.parse_amqp_url('amqp://guest:guest@localhost:5672').fetch(:vhost, '/')
 => "/" 
2.7.1 :006 > AMQ::Settings.parse_amqp_url('amqp://guest:guest@localhost:5672/').fetch(:vhost, '/')
 => "" 
2.7.1 :007 > AMQ::Settings.parse_amqp_url('amqp://guest:guest@localhost:5672/aaa').fetch(:vhost, '/')
 => "aaa"
```
