### ISSUE TITLE
`:ack` is deprecated.  Please use `:manual_ack` instead

### ISSUE THREAD

**Issue by NaixSpirit** [jondot/sneakers#93]
https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/queue.rb#L169

Using 0.10.0 w/ Bunny 1.6.0:
[DEPRECATION] :ack is deprecated. Please use :manual_ack instead.

**Comment by arrtchiu** [comment]
This is fixed in master already (#82), just not in the RubyGems version yet.

**Comment by NaixSpirit** [comment]
:+1:
