### ISSUE TITLE
Workflow suggestion: tag when releasing new gem?

### ISSUE THREAD

**Issue by rud** [jondot/sneakers#96]
There are now 11 releases at https://rubygems.org/gems/sneakers, but only 2 tags in the repo. Would it be possible to tag the git-repo when a new gem-version is created? That way it becomes easy to review changes, github supports it very well with urls like this: https://github.com/jondot/sneakers/compare/0.1.0.pre...0.1.1.pre

Just a suggestion, thanks!

**Comment by jondot** [comment]
Excellent suggestion - we'll make it so!

**Comment by abevoelker** [comment]
*cough* #34 *cough* :wink:

**Comment by SebastianEdwards** [comment]
The bundler gem tasks should push tags automatically when running `rake release`.

@jondot are you using bundler tasks to release new versions at the moment?

**Comment by jondot** [comment]
@SebastianEdwards I usually generate a gem with bundler and then release with 'rake build && gem push'. I'll definitely check out `rake release`.
I hope to cut a new version tomorrow with the recent updates :)

**Comment by jondot** [comment]
Thanks guys - I've just pushed 1.0.2 :+1: :+1:

**Comment by michaelklishin** [comment]
@jondot feel free to announce Sneakers releases on rabbitmq-users and ruby-amqp mailing lists :)

**Comment by rud** [comment]
Seeing the new tag, thanks @jondot
