### ISSUE TITLE
pid missing when spawning by worker group

### ISSUE THREAD

**Issue by Hippoom** [jondot/sneakers#98]
I'm trying to use the new spawner feature to [handling different workloads](https://github.com/jondot/sneakers/wiki/Handling-different-workloads).

I have two workers which are split into two groups:

<pre>
node_workers:
  classes: NodeActionsWorker
  workers: 2
job_workers:
  classes: JobActionsWorker
  workers: 1
</pre>

I start the ruby process to spawn workers 
``` bash
bundle exec ruby -e "require 'sneakers/spawner';Sneakers::Spawner.spawn"
```

The processes list below
``` bash
ps -ef | grep sneakers
  501 24223     1   0  2:26PM ??         0:00.17 ruby /Users/twer/Workspace/ScaleWorks/vendor/bundle/ruby/1.9.1/bin/rake sneakers:run
  501 24225     1   0  2:26PM ??         0:00.20 ruby /Users/twer/Workspace/ScaleWorks/vendor/bundle/ruby/1.9.1/bin/rake sneakers:run
  501 24226 24223   0  2:26PM ??         0:00.19 ruby /Users/twer/Workspace/ScaleWorks/vendor/bundle/ruby/1.9.1/bin/rake sneakers:run
  501 24227 24225   0  2:26PM ??         0:00.19 ruby /Users/twer/Workspace/ScaleWorks/vendor/bundle/ruby/1.9.1/bin/rake sneakers:run
  501 24232 24225   0  2:26PM ??         0:00.14 ruby /Users/twer/Workspace/ScaleWorks/vendor/bundle/ruby/1.9.1/bin/rake sneakers:run
```

So far so good, but when I cat the pids, I found the one of the pids is missing:

``` bash
cat tmp/pids/sneakers.pid
24225
```

Then I realize that the two work group share one global config:

<pre>
# in config/initializers/sneaker.rb

Sneakers.configure  :pid_path => 'tmp/pids/sneakers.pid', 
                                  ##other config items  
</pre>

I try to config pid_path within each worker, but it does not work.

**Comment by jondot** [comment]
Closing as this appears to be solved.
